### ISSUE TITLE
FAIL code

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1032]
I found some FAIL source code with this assignment:

$BEGIN←←.+1

Is there a way, using SUPDUP and EMACS, to write the double arrow ? 

thanks

**Comment by rmaldersoniii** [comment]
On WAITS, where FAIL originated, the left arrow is char # 137 (octal), since the extended character set is based on the original 1963 ASCII. In the 1967 standard, that code is the underscore character. (On TOPS-20, FAIL programs are full of A_10 and A__10 because of this.)
Try using "_" instead of "←". See what happens.

**Comment by larsbrinkhoff** [comment]
There may be, but I believe you should use _ instead of ←.

Did you see this source code on Saildart?  The web rendition of files makes some translations, _ to ← is among them.  There's also things done to control characters.

I recommend getting the octal blobs from Saildart instead, and translate them to ASCII with a tool we made for this exact purpose.

**Comment by TheFausap** [comment]
Yes @larsbrinkhoff I found some source code on Saildart. Where is that tool ? 

I found a FAIL manual on bitsavers: http://bitsavers.org/pdf/stanford/sail/STAN-CS-74-407_FAIL_Apr74.pdf
In this case I could use double "==", but I have a problem with the Arithmetic shift  : ⊗ 
so I think the best option is to get the octal blobs.

**Comment by larsbrinkhoff** [comment]
To get the octal blob, use this type of URL:  
https://www.saildart.org/SOMETHING_octal

Here's the converter:
https://github.com/larsbrinkhoff/pdp10-its-disassembler/blob/master/saildart.c

**Comment by TheFausap** [comment]
I translated the octal blob with saildart, but the arithmetic shift seems an unprintable characher... in ASCII
I got some strange glyph : 

![screenshot from 2018-06-27 21-36-32](https://user-images.githubusercontent.com/1846443/41995472-32b9e8ec-7a52-11e8-8cc2-b3529bcac458.png)

**Comment by larsbrinkhoff** [comment]
Here are some suggestions:

- Maybe it's ok, it's just your font missing that particular characters.
- What is that character?  E.g. in EMACS, type ^X = to see the code.
- What does it look like in Unix?
- What does it looks like without SAIL characters enabled?  What's the incantation... ^_ " (Conrol-underscore and double-quote) to toggle SAIL on and off.

**Comment by rmaldersoniii** [comment]
OK, here's a little file with translastions between Baumgart's Unicode substitutions, octal values, and modern ASCII.
The logical shift character is a ^V.
[Stanford_Character_Set.txt](https://github.com/PDP-10/its/files/2142735/Stanford_Character_Set.txt)

**Comment by TheFausap** [comment]
Thanks @rmaldersoniii ! In EMACS I can write this with ^Q^V  and it works.
