### ISSUE TITLE
DUMP speed differences between emulators

### ISSUE THREAD

**Issue by atsampson** [PDP-10/its#1100]
When working with tapes, I'd noticed that klh10 seems to DUMP much faster than it LOADs...

For a [current basics-only build on Travis](https://travis-ci.org/PDP-10/its/builds/408718282), here's how the time taken by the three emulators breaks down:

Emulator | Total | LOAD sources.tape | Build | DUMP output.tape
--- | --- | --- | --- | ---
simh KS | 9m34 | 0m22 | 5m45 | 1m02
klh10 KS | 21m01 | 5m46 | 8m21 | 1m41
sims KA | 31m40 | 7m31 | 7m03 | 7m44

So the (mostly CPU- or expect-input-bound) build stage takes about the same time on all the emulators - but why are the LOAD and DUMP times so different?

**Comment by larsbrinkhoff** [comment]
I don't know about KLH10 LOAD times.

Does DUMP include the ICHECK pass?  If so, that may in part explain why SIMH takes five times longer to do that.

As for KA, it simulates writing individual words with a reasonably realistic delay between each.  I tried to add the option to skip this delay, but it turned out to be harder than I thought and I decided to leave it alone.

**Comment by rcornwell** [comment]
For KA the speed of I/O operates much like the real KA10 in that data is read off the tape one character at a time. For SimH Bob reads/writes the whole block as a unit. I am not familiar with how KLH10 works. 

For the KA10 the TM10A was a polled type data transfer which means that bulk I/O is not possible. Also since the TM10A and TM10B are virtually identical other then one uses a DF10 and the other uses Polled mode. I did not feel it was good to separate the devices into two separate units. Other then Build/Dump time tape I/O is not used much so I did not see it as a problem.

Also as Lars said decreasing the delay time for TM10A caused problems with ITS messing itself up for some reason.

**Comment by larsbrinkhoff** [comment]
I tried to speed up the TM10B to kind of do block transfers.

The issue with speeding up TM10A is that it's interrupt driven and ITS doesn't like those interrupts at a high rate.

**Comment by atsampson** [comment]
Would there be any mileage in designing a "virtual tape" device that emulators and ITS could easily implement? (Or even a "host filesystem access" device...)

**Comment by larsbrinkhoff** [comment]
I think MLDEV should mostly solve that, but only for ITS of course.  It goes in the other direction, "guest filesystem access".

What's missing for the Linux MLDEV to be really useful is to present files using the evacuate format and to mangle file names exactly like itstar does.

**Comment by larsbrinkhoff** [comment]
But it doesn't speed up DUMP.  Which was the topic here.  Sorry.

**Comment by larsbrinkhoff** [comment]
@rcornwell tried to tweak the delay in the TM10A simulation.  ITS wouldn't have it.

The TM10B a drive to work out our problems peacefully.  It is, I believe, our last best hope for speedy magtape.

**Comment by rcornwell** [comment]
I would be interested in figuring out why ITS is corrupting data read from the tape if it comes in too fast. Tops10 does not have a problem with this. My suspicion is that ITS keeps interrupts off too long and the tape gets overrun.

**Comment by larsbrinkhoff** [comment]
Closing for now.  Reopen if there is more information to add.
