### ISSUE TITLE
MACSYMA bug (?)

### ISSUE THREAD

**Issue by TheFausap** [PDP-10/its#1211]
Hello,

I have a weird behaviour with bfloat macsyma function.
BFLOAT should convert a float number to big-float. I tested in a modern MAXIMA and everything is fine, but with out version of MACSYMA, I have this:
```
This is MACSYMA 1000

(C1) bfloat(0.2)
;
 
FLOAT FASL DSK MACSYM being loaded
Loading done
Warning:  Float to bigfloat conversion of 0.2

;ARITHMETIC OVERFLOW

Error during display

(C2) bfloat(0.3);
Warning:  Float to bigfloat conversion of 0.3
(D2)                         3.000000007450581B-1
```
I don't know if with KS this is an expected behaviour or is this an application bug or a CPU emulation bug.
It should be nice to test this on a real hw.

**Comment by eswenson1** [comment]
I tested on a real KS10 and got identical results. The FASL files running on the KS10 had been generated on an emulated system, so it is still possible that the compiled code is bad. Have you tried to narrow down the cause of the arithmetic overflow?  Does it happen interpreted and compiled?

**Comment by TheFausap** [comment]
I noticed, in the macsyma archive, there are two files named float:

- lmmaxq/float.qfasl.1
- rat/float.lisp.321

both of them are a BIGFLOAT library, but is it not weird the "version" number is so different ?
I'll try to load directly the float.lisp and I'll do the same test.

**Comment by TheFausap** [comment]
In the ITS repo, by the way, I found a newer version of float (under RAT directory) : float.329
Loading the lisp file,
```

macsym^K!
(C2)
This is MACSYMA 1000

(C1) loadfile(float,329,dsk,rat);

FLOAT 329 DSK RAT being loaded

DEFMAC FASL DSK LISP being loaded
Loading done

MLMAC FASL DSK LISP being loaded
Loading done

BACKQ FASL DSK LISP being loaded
Loading done

LETFEX FASL DSK LIBLSP being loaded
Loading done
Loading done
(D1)                                 DONE
```
I have no arithmetic flow error doing the same tests:

```
(C2) bfloat(0.3);
Warning:  Float to bigfloat conversion of 0.3
(D2)                         3.000000007450581B-1

(C3) bfloat(0.2);
Warning:  Float to bigfloat conversion of 0.2
(D3)                         1.999999992549419B-1

(C4) bfloat(0.1);
Warning:  Float to bigfloat conversion of 0.1
(D4)                         9.999999962747097B-2

(C5)
```
so it seems the compiled fasl file creates some problems.

**Comment by eswenson1** [comment]
That's interesting. The macyma in DB ITS does use a compiled RAT; FLOAT 329 and I've verified that using the interpreted version results in no arithmetic overflow.  I'm going to see if I can find a FLOAT FASL (329 or perhaps earlier) that was built on real hardware (e.g. MC) and see if it, too, has the problem. If it doesn't, then clearly our DB compiler has issues.

**Comment by eswenson1** [comment]
I retrieved a MACSYM; FLOAT FASL from MC dumps and used this instead of the one we build from RAT; FLOAT 329.  It did *not* have this issue. But checking the MC dump evidence, it seems that this working FLOAT FASL *was* built from RAT; FLOAT 329.  

So in a DB that already had MACSYMA build, I recompiled FLOAT 329 and tried again, and this time it worked fine.  So perhaps we have to do another one of these hacks -- after the macsyma build is complete, delete MAXER1;FLOAT 329, MUNFAS; FLOAT UNFASL, MACSYM; FLOAT FASL, and then recompile.  The compilation process will skip everything that is already built and just build FLOAT again.  My guess is that it should work.  I have no idea why the compiler is so flaky.  While trying to build the LISP; and LIBLSP; FASL files, I've noticed that I can only build so many FASL files in one run.  It isn't the number (that varies), but at some point, the next compile fails.  Restarting COMPLR and compiling the same file that previously failed will generally work just fine.  So something is getting corrupted in the compiler.  It may be the case that the same thing is happening with FLOAT -- the COMPLR session in which FLOAT is compiled might get corrupted (and generate bad code), but NOT raise an error.  It is the raising of an error that the expect macro build_macsyma_portion looks for to stop the current build and restart it.  

If you want, I can come up with some build steps to rebuild FLOAT so that you can get a working version.

**Comment by eswenson1** [comment]
Here are steps you can use to rebuild FLOAT:
```
*complr^K!
^G ;; type control-G here to break to lisp
(load '((libmax) module))
(load '((libmax) maxmac))
(maklap)
_macsym;_rat; float
^Z ; to return to DDT
```

**Comment by TheFausap** [comment]
I can confirm after the rebuild, it's working without any problem.
