### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1351]
All the cool kids are doing CD.

**Comment by larsbrinkhoff** [comment]
As it happens, I have my TT ITS up and running and it's a good target for experimenting with this kind of thing.

I'm not sure exactly how it would be done.  It wouldn't be appropriate to reboot into a fresh build *every* single commit.  But maybe once daily.

**Comment by atsampson-abertay** [comment]
It would be nice to have an "upgrade tape", that you could extract over an existing system without clobbering any configuration/data files. (I do this with the existing tapes on my system because I don't really have any configuration or data that I care about... but I'm guessing that wouldn't work for the public systems!)

**Comment by atsampson** [comment]
It would be nice to have an "upgrade tape", that you could extract over an existing system without clobbering any configuration/data files. (I do this with the existing tapes on my system because I don't really have any configuration or data that I care about... but I'm guessing that wouldn't work for the public systems!)

**Comment by larsbrinkhoff** [comment]
The upgrade tape was done in #1384.

I don't think it's realistic to deploy to a running ITS, so let's close this.
