### ISSUE TITLE
Early Emacs editors

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1354]
I believe the first Emacs copies were, in order:

1. EINE
2. SINE
3. Multics Emacs

I would like to collect some evidence here.

**Comment by larsbrinkhoff** [comment]
Some early EMACS file timestamps:

- .TECO.; ?MACS 171 - 1976-11-07
- EMACS; TS 16 - 1976-11-27

**Comment by larsbrinkhoff** [comment]
Placeholder for EINE information.

**Comment by larsbrinkhoff** [comment]
Anderson's SINE thesis:  
https://dspace.mit.edu/handle/1721.1/16038

**Comment by larsbrinkhoff** [comment]
Multics Emacs:

```
3/3/78
     1:00 PM.  A Demonstration of ITS EMACS is held on the CISL Delta
     Data 4000.  MC system is used, under heavy load, at 300 baud.

     Lack of organization, lack of preparation, hardware problems, low speed,
     load, and other difficulties contribute to an almost totally ineffective
     presentation.  Some, however, were impressed. C. Frankston,
     E. Killian, E. Ciccarelli, and others participated.

     ~3:00 PM.  Larry Johnson was impressed.  He says, "We should be able to
     do that", and devises a FNP (communications processor) patch that
     enables character-at-a-time input on Multics.  C. Frankston witnesses
     this.

     ~4:00 PM  In a conversation to C. Frankston, Greenberg muses,
      "you know, if we implemented that in flat-out PL/I, we could do that
       even better".
     A little consideration of modularity and extensibility soon leads to
     Lisp as a chosen implementation language.

     ~6:00 PM  SIPB Friday Night dinner is eaten at Colleen's.  Various
     parties throw around ideas about right way to implement such an editor
     on Multics.  The ideas of Bruce Edwards, who had recently implemented
     an editor in Lisp, stand out as important.

     ~10:00 PM C. Frankston drives Edwards and Greenberg to
     Brookline, in heavy snow.  Edwards visits Greenberg's apartment
     (he lives down the block).  They log in, and two hours, some beer
     and tty paper later, a functional editor in Lisp exists.  This
     program (e_) could build and split lines, insert and delete characters
     and lines, and move its pointer about.  It has no display or
     other output capability, and is driven by calls to Lisp functions.

**Comment by eswenson1** [comment]
Wow!  Never knew that story.

**Comment by larsbrinkhoff** [comment]
Thanks, I do see Finseth's work every time I do searches on Emacs history.  He still posts his list of implementations to comp.emacs occasionally.

**Comment by larsbrinkhoff** [comment]
Earliest file timestamp referring to EINE is LMDOC; EINED 5, dated 1977-11-09.

**Comment by larsbrinkhoff** [comment]
So we have:

- EMACS started in August 1976.
- EINE came before November 1977.
- SINE was "somewhat" before Multics Emacs.
- Multics Emacs started March 1978.
    SINE
    Multics Emacs

**Comment by larsbrinkhoff** [comment]
BUG-EINE mailing list.  First message is from "7 Jan 78".

https://ml.cddddr.org/bug-eine/

**Comment by larsbrinkhoff** [comment]
Link to SINE source code:

https://github.com/ArchMach/Sine

**Comment by larsbrinkhoff** [comment]
I have found EINE sources on ToTS tape 9004365.  Earliest timestamp is 1977-09-28.

**Comment by ams** [comment]
There is no mention of ZWEI here?

**Comment by larsbrinkhoff** [comment]
I consider Zwei more well documented elsewhere.  But do feel free to add information.

**Comment by larsbrinkhoff** [comment]
@johnsonjh, please add MINCE info here.

**Comment by johnsonjh** [comment]
Keeping in mind that I'm only an *accidental* "expert" (thus, not *actually* an expert) regarding all things **MINCE**, the following should be considered facts and can be verified by referring to **verifiable** sources:

## MINCE 1: 1979

- **MINCE** (version 1) was functional by [late 1979](https://en.wikipedia.org/wiki/Talk:Sprint_(word_processor)#3_Based_on_MINCE?). 
  - There only a few **tiny** fragments of pre-1980 **MINCE** code available, recovered from the "unused" areas of old disks.

  - While I do not (yet) have a more specific date for **MINCE** 1, it would have to be after the 1979 release of [CP/M 2.0](http://bitsavers.org/pdf/digitalResearch/cpm/2.0) and the August 1979 release of [BDS C](https://www.bdsoft.com/resources/bdsc.html).

## MINCE 2: 1980

- **MINCE** (version 2) saw commercial distribution in [September 1980](https://raw.githubusercontent.com/johnsonjh/pmince/master/legal/73576514.pdf); the earliest (*reliable*) dates for the creation of version 2 are [May, 1980](https://github.com/johnsonjh/pmince/blob/master/oemkit/mince/80/term.c).

  - Other dates in the source code are ambiguous but seem to indicate version 1 being complete by January 1980.

## Users Group

* The [AMETHYST-USERS mailing list](https://github.com/johnsonjh/pmince/tree/master/3rdparty/aug/mail) was on MIT-MC, as were the [AUG](https://github.com/johnsonjh/pmince/tree/master/3rdparty/aug/files) archives. I don't have much details from the "1st generation" AUG, but the "second generation" AUG was resurrected in the summer of 1982.

  * [AMETHYST](https://github.com/johnsonjh/pmince/blob/master/3rdparty/media/MINCEAD1.png) refers to a bundling of **MINCE**, [SCRIBBLE](https://github.com/johnsonjh/pmince/tree/master/oemkit/scribble/80), and BDS C.
```text
       13-Jul-82 23:55:00,984;000000000000
       Date:     14 July 1982 0155-edt
       From:     Brian N. Hess              <Hess.Unicorn at MIT-MULTICS>
       Subject:  Amethyst Users Group
       To:       Amethyst-Users at MIT-AI
       
       Quite a few people have asked about what ever happened to the Amethyst
       Users Group and the AUGment newsletter.  Well, after a long hiatus, they
       are about to be resurrected again.  For the time being, you can address
       AUG mail to Mark of the Unicorn rather than to the Texas address which
       you may have come to know and love.  Since the group should really be
       run by someone who's not a MotU person, are there any volunteers out
       there who have modified Mince a lot and have free time to devote to this?
       We're looking for a replacement for me...  If you've written to the
       Texas address, patience is the keyword -- we're going to revive the
       group somehow, but how quickly or what it will look like when
       reincarnated we don't know!
                                     Cheers,
                                     Brian
```
* As can be seen above, *MOTU* was assigned the "**Unicorn**" project on *MIT-MULTICS* (since at least mid-1982) - thus, the similarities between **MINCE** and Multics Emacs (*in my opinion*) cannot be accidental.
 
* In fact, **MINCE** users specifically noted the [similarity to Multics Emacs](https://github.com/johnsonjh/pmince/blob/master/3rdparty/aug/mail/8207-1.txt) as a major feature.

## Post-MINCE

* **MINCE** became the core of *Perfect* *Writer*. Indeed, *PW* was **MINCE** with many of the AUG enhancements built-in - the compiled editor core is about 6K larger than stock **MINCE** 2.6 on an 8080.  *Perfect* *Writer* was further enhanced to become *Final* *Word*.  *FW* was later purchased by Borland and became [Borland Sprint](https://en.wikipedia.org/wiki/Sprint_(word_processor)).

## Notable Users at MIT

*  MINCE/PW was in wide-use by the MIT community; Marvin Minsky [used it](https://github.com/johnsonjh/pmince/blob/master/3rdparty/aug/mail/9101-1.txt) to write "*The Society of Mind*".

## Further Information

- Everything that I know about MINCE can be found in the [Portable MINCE](https://github.com/johnsonjh/pmince) repository.

**Comment by johnsonjh** [comment]
A bit more info … DDJ and era interviews indicate that BDS C was working by January 1979 (at least in some state), and released around April 1979, earlier than previously mentioned above.

Leor Zolman was from MIT, the Unicorn guys were from MIT, and articles from this time indicate that others, all (obviously) connected with MIT as well, had been using the BDS C software before it was generally released as a product.

Indeed, an 01/1980 DDJ article mentions BDS C was available at that time, and that the Tiny-C people had been using it with success for quite awhile before that date.

A contemporary interview with Leor Zolman lines up, as he states he knew the Tiny-C people well (but was not aware of Small-C at the time.)

I'm considering writing him to ask if he might recall when he provided his software to the Unicorn people!

I normally wouldn't bother someone for just this kind of question, especially since BDS C history is well documented - and I sure wouldn't expect anyone to remember a sale from 42 years before, but, in this case, it's likely that the Unicorn people must have been among the very first users.

Also, the fact that the MOTU AMETHYST product actually bundled BDS C points to a special relationship, so it's likely worth asking. I'd not be surprised if Mark of the Unicorn was the very first reseller of BDS C.

So, it is a *possibility* that the first MINCE could have been any time after 01/79.

Now, I looked at many DDJ and BYTE scans, as well as the CP/M 2 source code comments, and can date the release of CP/M 2 to August 1979.

So, while it's possible that MINCE was begun earlier and adapted for CP/M 2, looking at the code makes me think it was not. Judgement call here too, but I've looked at **a lot** of CP/M code lately! 

This all also lines up with the "late 1979" recollection linked above.

Now, until definitive answers come back, this is nothing more than a somewhat well informed guess... but, based on the rate of development (as evidenced by the comments) and, assuming that work progressed more quickly at first than later on (well know fact that fixing bugs and polishing a release takes longer than getting the core functionality done, the 80:20 rule, etc)... I'd conclude, with high confidence, that the first workable version of MINCE must be dated to sometime between September and December of 1979.

**Comment by larsbrinkhoff** [comment]
I found a message to BUG-LISPM that DLW named the Lisp machine editor "EINE" on August 8th, 1977.

I see Lispm editor sources going back to 1975, predating EMACS by a year or so.  I wonder if it was more TECO-like at first, but morphing to be more like EMACS in 1977?

**Comment by larsbrinkhoff** [comment]
I see in a source file called "ED1" from February 1977 that the command set was already at that point similar to Emacs.  I found no useful Lispm editor before that.

**Comment by BobKerns** [comment]
Regarding Multics Emacs, I believe there's more to the story about the front-end hackery that came a bit later. (I'm pretty sure it was later than the character-at-a-time hack).

Rather than a character-at-a-time, the front end gained the ability to do local echo for straight typing, and only pass off input to the back end when an editing command or other exceptional condition arose (such as line-wrap). This cut the cost of using Emacs substantially and boosted its perceived responsiveness.

I think BSG was responsible for the hack? Or at least I learned of it from him? I think the story is probably to be found somewhere on multics.org.

**Comment by eswenson1** [comment]
Yes, BSG was responsible for the design and implementation.  There is a Multics MTB on the subject (MTB-418, https://multicians.org/mtbs/MTB-418.pdf).  The mechanism was called "echo negotiation" and is described in this MTB.

**Comment by larsbrinkhoff** [comment]
The earliest reference to ZWEI I can find is this message:

```
DLW@MIT-AI 11/14/78 19:18:50
To: EAK at MIT-MC
ZWEI is the second version of EINE, of course.  It stands for
Zwei Was Eine Initially.  It is a complete rewrite for about
six reasons which I will type in one of these days.  It wan't
announced in mail because everyone here heard about it by word
of mouth.
```
