### ISSUE TITLE
Amber, Chaos, and CAIOS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1358]
Try to untangle these names.  Why, how, when, who?

**Comment by larsbrinkhoff** [comment]
Mentions of CAIOS.

SYSDOC; CHAORD 57
> The messages transmitted through the ether (or CAIOS) net consist of

> a trailer rather than a leader is that the caiosnet hardware actually

> physics pdp11 in bldg. 38 and a pdp11 in 545, until the caiosnet

> gets extended that far (or a longer-distance, lower-speed caiosnet

SYSTEM; ITSDEV 974
> SUBTTL     INTERFACE (?) TO DM PDP11 ON NTY (REALLY WANT A CAIOS)

**Comment by larsbrinkhoff** [comment]
Hello @david-moon,

Do you know why the [Chaosnet memo](https://github.com/hanshuebner/cadr2/blob/master/mit/moon/amber.text) is named from the Zelazny book series?

Also, sometimes Chaosnet is referred to as Caiosnet.  Do you know why?

Thank you.

**Comment by david-moon** [comment]
> Do you know why the Chaosnet memo is named from the Zelazny book series? 


Lord of Light and Nine Princes in Amber came out around that time, and all 
we gnurd-boys were reading them and pretty impressed. Re-reading Lord of Light 
a couple years ago I detected some creakiness as well as Zelazny's usual overwriting 
but it still stands up pretty well. This was before there were actual Hindus in the 
American high-tech world, of course. 


At some point the background processes in ITS got named the Rakasha after the 
daemons in Lord of Light. 


I don't remember more specifically than that. 


> Also, sometimes Chaosnet is referred to as Caiosnet. Do you know why? 


I feel like I should know. It's probably an acronym. Jack Holloway probably 
named it that, but I don't know if he is even still alive. If he is, he probably 
does not remember. 


The only other thing I remember is that Chaosnet was an MIT response to 
Xerox PARC's Ethernet. We (not so much me) found out what they had done 
and said we can do that too, but better in some ways. No one was interested 
in compatibility back then. 


This message comes to you courtesy of Windows' incredibly slow C++ compiler. 
Otherwise I would be working.

**Comment by larsbrinkhoff** [comment]
Thank you!
