### ISSUE TITLE
Maclisp DOCTOR

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1493]
LIBLSP; DOCTOR FASL  
LIBDOC; DOCTOR JONL1

This seems similar to GAMES; ELIZA FASL.  Compare e.g. this from the source code:

```
(DEFPROP PROBLEMS
        (((0 ARE YOU PROBLEMS)
        (NIL)
        (EARLIER YOU MENTIONED 1)
        (LET/'S TALK ABOUT 1)
        (TELL ME MORE ABOUT 1)
        (YOU HAVEN/'T MENTIONED 1 FOR A WHILE)))
        MEMR)
```

with this generated by FASREAD from ELIZA FASL:

```
(EVAL DEFPROP PROBLEM (((0 (IS ARE) YOUR (PROBLEM PROBLEMS) 0) (NIL) (1 2 YOUR !
4) (ARE YOU SURE 1 2 YOUR 4) (PERHAPS 1 2 NOT YOUR REAL 4) (YOU THINK YOU HAVE !
PROBLEMS) (DO YOU OFTEN THINK ABOUT 1)) ((0 YOUR (PROBLEM PROBLEMS) (IS ARE) 0)!
 (NIL) (YOUR 2 3 4) (ARE YOU SURE YOUR2 3 4) (PERHAPS YOUR REAL 2 3 NOT 4) (YOU!
 THINK YOU HAVE PROBLEMS)) ((0) (NIL) (PLEASE CONTINUE/, THIS MAY BE INTERESTIN!
G) (HAVE YOU ANY OTHER PROBLEMS YOU WISH TO DISCUSS) (PERHAPS YOU/'D RATHER CHA!
NGE THE SUBJECT) (YOU SEEM A BIT UNEASY) NEWKEY)) RULES)
```

CC @jeffshrager

**Comment by larsbrinkhoff** [comment]
It was already added in #731.

**Comment by larsbrinkhoff** [comment]
How to run this, load LIBLSP; DOCTOR and run the WORKER function:

```
*:lisp
LISP 2154
Alloc? n
*
(load "liblsp;doctor")
127117
(worker)
SPEAK UP!
MEN ARE ALL ALIKE

IN WHAT WAY
```

The source code has this comment:

```
(COMMENT  DOCTOR SCRIPT - UPDATED TO /25 NOV /69)

**Comment by eswenson1** [comment]
Seems like ELIZA is an evolved version of DOCTOR, right?  ELIZA's PROBLEM seems to be more featureful than DOCTOR's PROBLEMS.  Agree?

**Comment by larsbrinkhoff** [comment]
Found this in https://www.saildart.org/INFO.ITS%5BUP,DOC%5D

```
THE DOCTOR PROGRAM

WEIZENBAUM'S "DOCTOR" VERSION OF ELIZA LIVES IN A OLISP VERSION
ON JONL;DOCTOR LSP AND IN A FASLOADABLE VERSION ON JONL;DOCTOR FASL.
DOCTOR IS A PROGRAM WHICH BEHAVES (SOMETIMES) OUTWARDLY LIKE A
ROGERIAN THERAPIST BUT ACTUALLY IS ONLY A COLLECTION OF TRANSFORMATION
RULES (WELL, ALMOST ONLY) KEYED BY PARTICULAR WORDS. THUS, IF
A KEYWORD OCCURS IN AN INPUT FROM THE USER, CERTAIN TRANSFORMATIONS
ARE APPLIED AND AN OUTPUT RESULTS. TRY IT AND SEE.
TO USE DOCTOR, DO OLISP↑K TYPE "N" FOR "ALLOC" AND
ONCE YOU GET THE PROMPT "*", DO "(FASLOAD DOCTOR FASL DSK JONL)".
THEN ONCE IT PRINTS AN OCTAL NUMBER, DO ↑G. INPUTS SHOULD BE
TERMINATED BY TWO CARRIAGE RETURNS.

**Comment by turbo** [comment]
> Seems like ELIZA is an evolved version of DOCTOR, right? ELIZA's PROBLEM seems to be more featureful than DOCTOR's PROBLEMS. Agree?

KMP [claims](http://www.maclisp.info/pitmanual/funnies.html):

> I didn't write the original ELIZA program, although my Lisp class was taught by Joseph Weizenbaum, who did. I later wrote a very elaborate program of similar kind, which I just called DOCTOR, in order to play with some of the ideas.

> At some point, I noticed there was a program at Stanford called PARRY (the paranoid patient), by Kenneth Colby. I understand from Wikipedia's PARRY entry that Weizenbaum's ELIZA and PARRY were connected at one point, although I never saw that. I never linked PARRY with my DOCTOR directly, but I did once do it indirectly through a manual typist. Part of my record of this exchange was garbled, but this is a partial transcript, picking up in the middle. Mostly it just shows PARRY was a better patient than my DOCTOR program was a doctor.

> I have done light editing to remove the typos we made (rubbed out characters were echoed back in square brackets).

> Also, I couldn't find documentation to confirm this, but my belief has always been that the numeric values after each line are PARRY's level of Shame (SH), Anger (AN), Fear (FR), Disgust (DS), Insecurity (IN), and Joy (J).—KMP

Transcript:

```text
... I WOULD APPRECIATE IT IF YOU WOULD DESCRIBES SOMETHING ABOUT YOUR INHIBITIONS.

 DO YOU KNOW WHAT YOU'RE DOING?

 (SH 0.20 AN 0 FR 2.47 DS 0 IN 5.81 J 7.39)

 Ready: PERHAPS YOU COULD ALLOW ME TO DO THE QUESTIONING. 
        PLEASE TELL ME ABOUT MORE ABOUT SOME SOME PROBLEMS IN YOUR CHILDHOOD.

 I KNOW WHO THE LOCAL CHIEF OF THE MAFIA IS

 (SH 0.29 AN 0 FR 2.07 DS 0 IN 6.63 J 7.58)

 Ready: WHAT MAKES YOU THINK YOU KNOW WHO THE LOCAL CHIEF OF THE MAFIA IS?

 MAYBE THEY ARE GLAD I AM IN THE HOSPITAL

 (SH 0 AN 0 FR 2.45 DS 0 IN 6.60 J 6.78)

 Ready: IS IT BECAUSE OF THE PEOPLE YOU HANG AROUND WITH THAT YOU SAY
        MAYBE THEY ARE GLAD YOU ARE IN THE HOSPITAL.

 THEY WANT TO GET FALSE EVIDENCE TO FRAME ME

 (SH 0 AN 0 FR 2.79 DS 0 IN 6.58 J 5.98)

 Ready: WHY DO YOU SAY THEY MIGHT WANT TO GIVE?

 THAT'S JUST THE WAY IT IS

 (SH 1.45 AN 0 FR 3.00 DS 0 IN 6.81 J 5.81)

 Ready: PERHAPS THIS HAS SOMETHING TO DO WITH PROBLEMS AT SCHOOL?

 MY EDUCATION WAS OK

 (SH 1.25 AN 0 FR 2.80 DS 0 IN 6.61 J 6.27)

 Ready: WHAT MAKES YOU BELIEVE YOUR EDUCATION WAS OK?

 I WENT INTO THE SERVICE AFTER GRADUATION

 (SH 0.85 AN 0 FR 2.40 DS 0 IN 6.58 J 6.25)

 Ready: EARLIER YOU SAID THEY WOULD LIKE TO GIVE?

 SOMEBODY SHOULD TEACH YOU A LESSON ABOUT INTERVIEWING

 (SH 0.55 AN 0 FR 2.10 DS 0 IN 6.28 J 6.43)

 Ready: POSSIBLY YOUR SEX LIFE ARE RELATED TO THIS?

 I WOULD RATHER NOT DISCUSS SEX

 (SH 0.82 AN 0 FR 1.90 DS 0 IN 6.84 J 7.35)

 Ready: ARE YOU AFRAID OF SEX?

 MY SEXLIFE IS MY OWN BUSINESS

 (SH 0.62 AN 0 FR 1.70 DS 0 IN 6.64 J 7.52)
```

**Comment by jeffshrager** [comment]
In order to maximize confusion, the "original" Lisp Eliza, written by Bernie Cosell @at BBN -- which is NOT the original Eliza, that having been written in MADSLIP and apparently lost to history -- had 2 parts: Eliza is the meta-program that runs scripts, and the script that everyone knows was called "doctor". If you have your doctor program, Kent, I'd be excited to be able to add it to the Eliza Genealogy Project (elizegen.org)!

'Jeff 

----------
Jeff Shrager, PhD
Director of Research, xCures
and Adjunct Professor
Symbolic Systems Program
Stanford University


________________________________________

**Comment by larsbrinkhoff** [comment]
I don't think Kent is listening in yet.

@netsettler, your version of DOCTOR was mentioned in this GitHub issue.

**Comment by turbo** [comment]
@jeffshrager Sadly, I'm not Kent Pitman, hence the "KMP claims" followed by a quote.

The quoted passage appears on his website, the Pitman manual. The Pitman manual is the most complete MACLISP reference to date since it covers a wide variety of MACLISP flavors via annotations.

**Comment by jeffshrager** [comment]
Missed that pointer; Thanks, I'll try to contact Kent elsewise.

----------
Jeff Shrager, PhD
Director of Research, xCures
and Adjunct Professor
Symbolic Systems Program
Stanford University


________________________________________

**Comment by netsettler** [comment]
My version of DOCTOR was written from scratch, and to my knowledge was not something someone incorporated into something else, so it will have a lonely place in any genealogy but may still be of historical note.  It ran on the MIT ITS computers, MIT-MC in particular, but I'd have to check if it's in the ITS sources or if I have a version of it, perhaps even in hard copy, though such is fragile. Sometimes when I've checked, the pages stick together. It did not have the two-part structure Jeff is describing, exactly, though I suppose it did have a set of pattern-driven actions, since that was how we were taught to make these things. I'm pretty sure it did not use the data structure illustrated at top of this thread (from LIBLSP). My recollection (and you know what these are worth, I could be blurring things) is that I was interested in transformational grammars and might have used the same or a similar pattern engine that I had also evolved for an ANIMAL program ("guess an animal", an idea also not original with me, just the implementation). The two had conceptual overlap and may have shared libraries, but I don't recall. It probably wasn't as clean in practice as I want to make it in my mind. :) It's actually possible ANIMAL had a better parser than DOCTOR, which would seem weird for a yes/no decision-tree kind of program, but it allowed way more than yes/no. The pattern technology was an elaborated version of something we had been asked to write as problem sets in 6.034, taught by Winston, Horn, Fredkin, and maybe others. There's quite a long and expansive story on both of these I should write up as a blog post as it'd probably be fun for people, but it would be excessive in this forum probably.

**Comment by turbo** [comment]
@netsettler 

> There's quite a long and expansive story on both of these I should write up as a blog post as it'd probably be fun for people, but it would be excessive in this forum probably.

I've been enjoying the "funnies" section and would very much like to read more about the history and quirks of those programs. BTW, thank you for hosting your edition of the MACLISP manual - it has been instrumental in a software preservation project I'm involved in. /ot

**Comment by netsettler** [comment]
I should add that I also took my intro to lisp (6.030) course from at MIT from Weizenbaum and others. Among the tricks of memory, there is some possibility that we learned some of the Eliza stuff from him. So there is a conceptual lineage. But I feel like the match technology came from the AI intro course (6.034). It was such a rich environment of so many ideas that I'd have to do a lot of poking about in saved documents to sort out. I'm happy to see someone doing the work of creating at least some record. A worry of mine is that, if humanity survives climate change at all (a big if), future historians will look back on the web to a point in time where they say "and then suddenly all information was simultaneously present", an informational big bang, before which there was only paper and poor record keeping. Comparatively nothing will be known beyond that cliff and the details of how the world bootstrapped itself to the point where it was ripe for the web, by having ubiquitous computation, by having decent networking and editing technology, and a sea of good ideas frothing around waiting to congeal, are going to be things that are captured, if at all, by the people doing this painstaking historical preservation stuff.

**Comment by larsbrinkhoff** [comment]
@turbo, which project is that?  This?  https://github.com/turbo/netlisp

**Comment by larsbrinkhoff** [comment]
@netsettler, thanks for your comments.  ANIMAL is also in here somewhere.

Maybe ITS should be carved onto rune stones to ensure it's future survival.  It could be the operating system for the next human civilization.

**Comment by netsettler** [comment]
Ha, I told you memory was unreliable, so now I get to contradict myself on some points. I have located a version of the doctor program that looks so old and ugly that I didn't initially recognize it as mine, but it has unmistakable fingerprints of things I would have done at various points in the code, such as (1) a "winners" list that includes me and members of the Mathlab group, who worked on Macsyma, as being the only ones able to run it during loaded daytime hours), (2) use of macro libraries that I used and had limited adoption by others, and (3) various add-on weirdnesses like sending me personally an interactive message if I was logged in when anyone started playing and sending them a bill when they were done. :)

The structure of some of the code is so bad I want to blame it on someone else, so I'm hoping we'll find there is code overlap with someone else's version, but I don't really think so.  I guess it just didn't get much attention, as I had a lot of other things to do.  I'm pretty sure the feature I cited as item 3 above is one of the last "enhancements" I made to it, so while there could be a later version, this is probably scarily new. I just cringe at code that uses TYO with decimal integers instead of the #/ readmacro, or even FORMAT. Even scarier that I still know those codes.  And the indentation is grossly awful, even though I wrote a nice indentation library for TECO-based Emacs that could have indented it better. :(

There may be a conceptual overlap or a small kernel of something I got from class, because certain things on the very innermost part are namings I don't remember using, but then I didn't remember a bunch of this, so it's hard to say.

The version of the file is something I don't have a full chain of custody for either. I got it from Chris Stacy by email on 30 Dec 2001 and he says he found it at ftp://philbudne.ne.mediaone.net/pdp10/maclisp/doctor.lsp which I don't know anything about. I don't know whose site that was. But maybe that was some pdp10 repository that someone will recognize from the URL even if it doesn't exist now.

It's just one file, though it depends on other libraries that hopefully have compatible versions available, in particular: LISP;LET, LISP;DEFMAX, LIBLSP;IOTA

The question is where an appropriate place would be to upload it.

**Comment by larsbrinkhoff** [comment]
That FTP site is now here: ftp://ultimate.com/pdp10/maclisp/  @philbudne is hosting it.

The closest thing to a doctor.lsp in see is JONL; DOCTOR LSP.  We don't have that file, but we do have LIBDOC; DOCTOR JONL1 and DOCTOR JONL2 here: https://github.com/PDP-10/its/tree/master/src/libdoc  However, they are nothing like doctor.lsp.

There is a file called KMP; TS DOCTOR.  It wants to load BMT1; DOC (INIT).  If found a BMT1; DOC 102 and linked it from the init file.  It's a close match to doctor.lsp.  When TS DOCTOR is run, it says:

```
*:kmp;doctor


The doctor will be ready in a sec... When he is ready,
he will say so. Please end responses with
a period.
                Be patient!
                       -The Doctor's Secretary

This is not the time of day to be playing games!
Please come back later. This game is unavailable
during the hours of 9am-8pm Monday-Friday.
```

With a little coaxing:

```
:chuname kmp
:doctor


The doctor will be ready in a sec... When he is ready,
he will say so. Please end responses with
a period.
                Be patient!
                       -The Doctor's Secretary

I AM THE PSYCHIATRIST. PLEASE, DESCRIBE YOUR PROBLEMS.

**Comment by turbo** [comment]
> @turbo, which project is that? This? https://github.com/turbo/netlisp

No, it's not yet public. It's not one project, but bits and pieces from older MACLISP programs.

Although franzlisp (of which netlisp is simply a distribution) is essential in the process. You see, translating *MACLISP* programs to *Franz Lisp in MACLISP mode* is almost effortless (most changes have to be made to account for vastly different I/O on BSD vs. ITS). Franz Lisp, through the BSD's maintainer's obsession with binary backward-compatibility, is still able to run on modern BSD even without recompiling.

So my workflow is to try to get most of the code running on ITS, mostly just to understand it but then translate it to FL as soon as possible to separate the code and it's ideas from the fangs of ITS ;)

NetBSD 8 with FL and this ITS emulation installed would be the perfect MACLISP archivist's distribution by the way. But I haven't gotten ITS to build even in BASICS mode on BSD (lot's of small differences need to be corrected and compile switches created in some of the submodules). I'll try again if I have some more time.

**Comment by larsbrinkhoff** [comment]
> No, it's not yet public. It's not one project, but bits and pieces from older MACLISP programs.

I'd love to hear all details if or when (or before) it goes public.

**Comment by netsettler** [comment]
Lars, the interaction you describe sounds right, but I don't see a BMT or BMT1 directory in the source tree you referred to, so I couldn't check the source. (I'm surprised they're in that directory.)

**Comment by larsbrinkhoff** [comment]
Sorry, the online location is here: https://github.com/PDP-10/its/blob/master/src/games/doc.(init) and there's a second copy: https://github.com/PDP-10/its/blob/master/src/games/doc.102

As for why they were in the BMT1 directory, it's my impression, but maybe @eswenson1 can confirm, that this was the unofficial directory for games on MC.

**Comment by eswenson1** [comment]
Yes, on MC, BMT1 had the sources/binaries/fasl files/init files for a bunch of the games. Not all games were hosted there, however, and it is quite possible that doctor was somewhere else. Also, I think *we* created the GAMES directory (that wasn't on MC) to collect a bunch of the random games that were hosted in individual people's home directories. It is probable that *we* put doc.102 under games because my records indicate that on MC, DOC 102 was under BMT1;.  Not sure why it ended up under GAMES in the DB distribution, since we do have a BMT1 directory there.

**Comment by netsettler** [comment]
I'm betting my doctor program was originally in TURNIP, and it might have gotten moved if we weren't originally distributing that directory. It doesn't matter a whole lot to me. 

At first glance, the data in the cited file looks like the file I have. I'm not where I can check now, but will a bit later and will update here.

**Comment by eswenson1** [comment]
I just checked backup dump records and see that DOC 102 on MC was in the BMT1 directory (and not KMP or TURNIP).  Here is some data that supports this:

```
 directory | fn1 | fn2 |   tid   |   tid   |                      info
-----------+-----+-----+---------+---------+------------------------------------------------
 bmt1      | doc | 102 | 7005153 | 7005153 | BILD;.FILE. (DIR)       Nov 16 1983
 bmt1      | doc | 102 | 7005645 | 7005645 | BILD;.FILE. (DIR)       Aug 08 1983
 bmt1      | doc | 102 | 7006658 | 7006658 | Tape 4045, reel 8, created 04/24/86, type=full
 bmt1      | doc | 102 | 7006707 | 7006707 | Tape 3670, reel 8, created 04/24/85, type=full
 bmt1      | doc | 102 | 7006902 | 7006902 | BGL;.FILE. (DIR)        Feb 13 1984
 bmt1      | doc | 102 | 7006924 | 7006924 | Tape 3775, reel 8, created 06/25/85, type=full
 bmt1      | doc | 102 | 7007354 | 7007354 | Tape 3616, reel 8, created 03/13/85, type=full
 bmt1      | doc | 102 | 7007742 | 7007742 | Tape 3503, reel 3, created 01/09/85, type=full
 bmt1      | doc | 102 | 7008026 | 7008026 | Tape 3720, reel 7, created 05/19/85, type=full
 bmt1      | doc | 102 | 7008073 | 7008073 | Tape 3990, reel 8, created 01/16/86, type=full
 bmt1      | doc | 102 | 7008199 | 7008199 | Tape 3320, reel 8, created 04/27/84, type=full
```

**Comment by eswenson1** [comment]
And while I see no "doctor" under kmp; or turnip;, I do see these:

```
 directory | fn1 |  fn2   |   tid
-----------+-----+--------+----------
 kmp       | doc | 1      | 90609
 kmp       | doc | 1      | 7007837
 kmp       | doc | 1      | 90605
 kmp       | doc | 19     | 7005539
 kmp       | doc | 19     | 7005540
 kmp       | doc | 20     | 7005539
 kmp       | doc | 20     | 7005540
 kmp       | doc | 59     | 7007766
 kmp       | doc | 60     | 7007766
 kmp       | doc | 62     | 7006983
 kmp       | doc | 62     | 701366-1
 kmp       | doc | 62     | 701366
 kmp       | doc | fasl   | 7005539
 kmp       | doc | fasl   | 7005540
 kmp       | doc | source | 701366-1
 kmp       | doc | source | 7006983
 kmp       | doc | source | 701366
 kmp       | doc | source | 7007766
```

**Comment by larsbrinkhoff** [comment]
GAMES was first created for ADVENT.  The oldest version which never was on any iTS machine.

I seem to recall we discussed this at some point and decided it was logical to add more games to GAMES rather than BTM1.

**Comment by eswenson1** [comment]
Yes, we did. My earlier comment was really for everyone else's benefit -- rationalizing the name GAMES and why files that were originally in BMT1 and other home directories were "moved" to GAMES in DB.

**Comment by netsettler** [comment]
I have diffed GAMES;DOC 102 with the version I have here locally that @cstacy mailed me in 2001 and it looks like an older version than the one you have, but trivially so.  The changes are:

(1) In mine it doesn't have CSTACY in the list that begins TNP KMP RWK MRG ... of people who can run it in daytime.

(2) In mine there is a test for (AND (NOT (EQ (STATUS USERID) 'KMP)) (PROBEF '((USR *) KMP HACTRN))) that is wrapped in the newer one with a MAPCAR that is willing to look for an OBSERVER rather than the constant 'KMP so that CSTACY can be in the list.

(3) Some formatting is changed in one place where it was messy.

(4) There is an *echostream* added, I think for the purpose of letting you set it to NIL if the input device is doing its own echoing.

I could send the precise diffs, but a conceptual summary seemed more friendly.

Anyway, to me, it looks like the changes are all legit changes that CStacy probably did contemporaneously, and so mine is of questionable value. I don't know what version mine would be since he only sent me the text, not the filename.

**Comment by larsbrinkhoff** [comment]
Thanks @netsettler, I got the file by FTP from ultimate.com.  The file came from one of Phil Budne's magtapes.  It was named KMPDOC.LSP and timestamped 4-Aug-80.  He wrote me:

> It's from when I was at Stevens Tech, and fooled with MACLISP on TOPS-10.  The maintainer (KMP?) would send me MACLISP (9-track) tapes, but the file could have been downloaded by other means.....
