### ISSUE TITLE
Prolog

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1518]
PDP-10 Prolog, by Warren, Pereira, and Pereira.

**Comment by larsbrinkhoff** [comment]
Hello @earnmyturns,

I'm researching and restoring PDP-10 software.  Do you know if PDP-10 Prolog has been preserved?

Thank you,
Lars Brinkhoff

**Comment by atsampson** [comment]
farad and I did some digging around this on IRC back in December - it looks like [this Prolog implementation on SAIL](https://saildart.org/allow/%5bPRO,SYS%5d) is the Warren/Pereira/Pereira one, and it's not in [Edinburgh's archive](http://history.dcs.ed.ac.uk/archive/languages/prolog/). Note that SAIL's copy has some local modifications but the earliest versions of the files look intact.

**Comment by earnmyturns** [comment]
My daughter found a complete version with executables for TOPS-10 that she
made work on an emulator on a Raspberry Pi as a Christmas present for me.
I've been traveling for the last several weeks, I'll dig into what she got
for me when I have more time.

**Comment by larsbrinkhoff** [comment]
"Tiny PROLOG"

```
; This is a tiny PROLOG interpreter that is based on an even
; tinier PROLOG interpreter written in MACLISP by Ken Kahn.
```
https://www.t3x.org/s9fes/prolog.scm.html

**Comment by pmcjones** [comment]
@atsampson So do you believe the saildart.org files represent a complete copy of the system?

@earnmyturns Have you had a chance yet to look at the version your daughter gave you?

I ask because I'm starting a collection of early Prolog source code (and documents) for the Computer History Museum in Mountain View. I'm relatively new to Prolog/logic programming, but my friend Maarten van Emden is consulting on the project, and I've had past experience with similar projects (e.g., http://www.softwarepreservation.org/projects/LISP/). So far I have a listing of David H.D. Warren's 1975 compiler written in the Marseille dialog (courtesy of Maarten and David), ODRA Prolog from 1983 which is derived from the Marseille system (upgraded to Fortran IV logical IF statements from the original Fortran II arithmetic IF statements, etc.) So I'm excited about the existence of the PDP-10 Prolog source code.

Paul McJones
paul@mcjones.org

P.S. Thanks to @larsbrinkhoff for bringing this all to my attention.

**Comment by atsampson** [comment]
@pmcjones I don't know, I'm afraid. The earliest versions of the files look plausible but I've not tried getting them up and running.

**Comment by pmcjones** [comment]
@atsampson , @earnmyturns told me offline that indeed his daughter started with the saildart.org files, but had to do some more work to get it running. I'm hoping to talk to her, and will post what I learn.

**Comment by larsbrinkhoff** [comment]
There's another set of files here:  
https://saildart.org/[PL,SYS]

**Comment by pmcjones** [comment]
Also https://www.saildart.org/LOG looks like a release tape from 1981 (no source code).

**Comment by pmcjones** [comment]
And yet another set of files (including source) here: 201 source and executable files in 3,491,545 bytes, 1982-1984: https://www.saildart.org/[*,PL]/
