### ISSUE TITLE
Change pdp10-kl build to use TM10B

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#1699]
TM10A has proven unreliable with the pdp10-ka emulator.  Since the pdp10-kl is intended to closely match what MIT-MC was running, and since MC used a TM10B tape drive, it seems reasonable to update the pdp10-kl build to use TM10B.  

If we need a testbed for TM10A, perhaps we should change the KA (pdp10-ka) build to use TM10A -- but perhaps not until we get TM10A working reliably.

**Comment by rcornwell** [comment]
Eric, the only difference between the TM10A and the TM10B is that the TM10B uses a DMA device to transfer data, the TM10A uses a irq per word. Make sure you have MPX set correctly on TM10A, otherwise interrupts will not be handled correctly. The only reason I can think of that TM10A does not work is that ITS keeps the PI level raised for too long an interval, since the errors typically are lost data. Both versions of TM10 work very well on Tops 10 (many versions)

**Comment by eswenson1** [comment]
These are the settings I have for TM10B:
```
set mta mpx=7
set mta type=b
```
When I switch to "set mta type=a", should the "set mta mpx=" change, or stay the same, or be removed?  I believe I've been using it with "set mta mpx-7", but it is possible that since this wasn't in the original pdp10-kl build scripts (I added it based on your comments to me in IRC) that when I did the TM10A testing, I might not have had it.

**Comment by larsbrinkhoff** [comment]
If mpx was wrong, I think it should have failed more throroughly.  It should be the same no matter if the type is A or B.

**Comment by larsbrinkhoff** [comment]
@rcornwell, as you recall, we tuned the TM10 sim_activate delay to be as low as possible without triggering an error in the ITS build.

This "new" problem is that the final moby dump goes wrong.  When we tuned the delay, we didn't check this dump.

**Comment by larsbrinkhoff** [comment]
AI and ML used TM10A controllers; DM and MC used TM10B.  So I have tried to exercise both mta type=a and type=b in the build.  It's still used in a lesser capacity: bootstrapping KA ITS.  TM10A is used initially before the new ITS has been assembled.
