### ISSUE TITLE
Emacs says "IFN     Illegal FS flag name?"

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1771]
Whenever I try to execute some TECO code from Emacs, I get the message `IFN     Illegal FS flag name?`

Example 1:  type M-% for query replace.  Enter a string, altmode, another string, double altmode.  A wild error message appears.

Example 2: Type double altmode.  Enter e.g. 65I$$ to insert ASCII character 65 into the buffer.  Same error message.

**Comment by eswenson1** [comment]
Interesting. I don't have this issue on ES.  I'll boot up a KL and see if I see it there.

**Comment by eswenson1** [comment]
The code is failing here:
```
!^R Execute Minibuffer:! !^R Read and run TECO commands.
Uses the minibuffer to read them.  Pushes the command string
onto a ring buffer in Q.N.  An explicit argument initializes
the minibuffer with the command from the top of that ring buffer.
Once inside the minibuffer, ^\^R Prefix Control-Meta^\ C-Y pops to previous saved
minibuffer commands, going around the ring.!

    m.m ^R_Pop_Minibuffer_Ring^[[...^RY
    q..o,( f[b bind^[
         f^Xf^Y"n g:.n(0)'      !* Make new buffer, maybe fill with previous string.!
         )m(m.m &_mini buffer^[)Minibuffer^['    !*read stuff in new buffer, with old as arg!
    h^@"e 0^\'              !* Buffer empty =) user ^Gd, so do nothing.!
    f=(q:.n(0)f"e w :i*^[')^]^S..o^["n  !* If this command not same as previous minibuffer,!
      q.n[..o zj-5d         !* push this command onto ring buffer of!
      j 5,0i ]..o           !* minibuffer commands.!
      hx:.n(0)'
    f]b bind^[ ]...^RY m:.n(0) w^\   !* In any case, run it, after restoring normal environment!
```
I believe on the "e w :i*" command.  Of course, this is all Greek to me. There is no "e" command -- "e" is a prefix character, so I think the command is "ew", which opens a file for writing.  The output device is specified by the string that follows the "ew" command.  But what follows is :i*, which, I believe inserts into Q register * the string that follows this command -- terminated by ^[.  So that would suggest that the empty string is being put into the * Q register.  

As I said, I don't know what I'm talking about (the last time I wrote Teco code was when I edited my emacs INI files back in 1980, or maybe earlier.

**Comment by eswenson1** [comment]
The first string used in the comparison is the vector in .N, element 0 ( .n(0) ).  In my backtrace, it appears the contents is empty. I guess that makes sense, since this is a new emacs and I'd never used the minibuffer (or any other buffer) before.  

The F"E...' conditional is like regular conditionals, but returns its argument whether the comparison succeeds or fails.  I guess this must be checking to see if the .N(0) value is empty -- which it is.  Hence we execute the body of the F"E...' conditional.

So I was wrong, above, when I said that the E"...' clause means that they were the same. I was thinking that the comparison indicated equality.  In fact, we're still evaluating the first argument to the F= command, and finding that .N(0) is empty.  So I don't understand the W :i*^[ part, since that appears to be inserting the empty string.  

I guess I should just stop butchering this analysis and let a real TECO person take a crack at it.

**Comment by eswenson1** [comment]
By the way, I remember seeing this error crop up when I was trying to build NEX.  I finally did succeed (I just ran NEX and was able to execute teco commands in the minibuffer).  I vaguely remember that it had to do with building an EMACS library with PURIFY when I should have used IVORY, or vice versa.  I spent a long time debugging this and finally succeeded.  Unfortunately, I have no recollection of WHICH library I had generated incorrectly....

**Comment by eswenson1** [comment]
Question for anyone:  What does :i* do?  The documentation for :I says that it takes a q-register name immediately after the I.  So that would suggest that * is a q-register name. However, attempting to display the contents of that q-register (say, in a backtrace) says that * is an invalid q-register name.  I don't see * as a modifier for :i. Does it mean something special?

**Comment by larsbrinkhoff** [comment]
Since the error is "illegal FS flag name", shouldn't there be a variable named FS something triggering the error?

TECO ORDER says:
> The command :I*<string>^[ returns a pointer to a newly consed up string containing <string>.

So the code `:i*^[` is just an empty string.

**Comment by eswenson1** [comment]
Hmmm.. I wonder why I didn’t find that in the larger TECO documentation.

One other thing to note: I built a NEX on ES, initiallly. But then, since I use it there rather than EMACS, I wanted it on EX — which was then just a KA with networking — and got it to build and run there too — without the illegal flag name error on query replace (which I use all the time).

This means that building NEX on KA/KL/DB — with our build script does allow a NEX to be built without this problem. This suggest an error in our build/dump process. It would be interesting to compare the EMACS and NEX build processes to see where they differ. That would probably point to the problem. NEX is largely EMACS — it shares a lot of libraries. But it also uses a different initialization/dump set of files.

**Comment by eswenson1** [comment]
And yes, I wonder why the backtrace doesn’t point to an FS flag name directly?

**Comment by eswenson1** [comment]
Interesting. If you just start TECO after setting EMACS as the xuname (emacs$^S), you will get the same error. And if you do a backtrace, you can see that spaces have been removed where they shouldn't be.  One of the libraries we have in our build, and which is loaded by the TECO init, is bad.

I tried running TECO on ES and I get the same error -- so I suspect that if I dumped out an EMACS using our current libraries (which I've updated on ES), I'd also have the same problem as in DB/KL/KA.

**Comment by eswenson1** [comment]
I just moved the TECO sources (1213) to ES and rebuilt TECO.  Using that TECO, I dumped out a new Emacs (on ES).  It does not have the issue that the one on DB/KL/KA has.  I don't get an error when, in a minibuffer, I do 65$i.  I think that means that either EMACS;EMACS :EJ or EMACS:EINIT :EJ are bad on DB/KL/KA.  I'm going to replace each with the one from ES and see if I can get things to work. Once I isolate the one that is breaking EMACS, I'll compare. I believe I found that the code that is failing comes from & Load Essential Environment (in EINIT).

**Comment by eswenson1** [comment]
Well, it wasn't EMACS;EINIT :EJ.  I replaced that file on KL with the one from ES and had the same issue with a newly dumped emacs.  So then I replaced EMACS;[PURE] 163 (on KL) with the one from ES and dumped a new emacs. I can now run teco commands from the minibuffer.  So there must be something wrong with the EMACS;[PURE] 163 we are building.  Comparing the two EMACS;[PURE] 163 files shows lots of differences.

**Comment by eswenson1** [comment]
Hmm.... everything is working for for me now on KL.  And I'm not exactly sure what I did.  I did find that the AUX :EJ was causing me troubles until I rebuilt, but I'm not sure that was the issue.  Unfortunately, I believe I've overwritten some of the original KL files and will have to start over with a fresh build before I can be sure of what is going on.  In any case, I no longer have the issue on KL and can rebuild emacs with no issues either.

**Comment by eswenson1** [comment]
So I've narrowed it down.  It is the EMACS;[PURE] 163 file.  The one generated from our build is different from the working one on my ES system and when I replace it with the one from ES and dump out a new emacs, the resulting TS file works fine (no issues with evaluating TECO expressions in the minibuffer).  So next, I'm going to look at the files loaded and included in EMACS;[PURE] 163 to see which ones differ and attempt to narrow down the culprit.

**Comment by eswenson1** [comment]
One difference is that on ES, I have EMACS1;FILES 434 and we have EMACS1;FILES 435 in our source tree.  Also, ES has EMACS1;ISEARC 74 and we have EMACS1;ISEARCH 75.

I replaced EMACS1;FILES 435 with EMACS1;FILES 434 and recreated EMACS;[PURE] 163 and EMACS;TS 163.  Now, emacs doesn't have the isssue any more.  So it appears to be EMACS;FILES 435 that caused the issue.  Now trying to understand why.

**Comment by eswenson1** [comment]
This looks suspicous:
```
**** FILE DSK:EMACS1;FILES 434, 23-8 (32700)
    .,.m(m.m&_Save_for_Undo◊)Insert_File◊
**** FILE DSK:ESAVE;FILES 435, 23-8 (32674)
    .,.m(m.m&_Save_for_Undonsert_File◊
***************
```
Not sure why this would break the way we're seeing it break, but it doesn't look right.

**Comment by eswenson1** [comment]
Well, fixing that issue (Save for Undo) doesn't make the Illegal FS flag name? error go away.  So I may have to do a binary search on the other changes to EMACS;FILES.

**Comment by eswenson1** [comment]
Looking at the other changes to FILES, I see lots of "FS XXX" flags that don't appear to be terminated with an $.  I suspect this is the source of the problem.  In particular, this diff seems germane:
```
**** FILE DSK:EMACS1;FILES 434, 1-43 (1919)
            FS PJATY◊+1"G :FT------------------------------◊ 0U..H '
**** FILE DSK:EMACS1;FILES 436, 1-43 (1919)
            FS PJATY"G :FT------------------------------◊ 0U..H '
***************
```
There the above code is involved in displaying minibuffer dashes.  There are other similar problems too.

**Comment by eswenson1** [comment]
Looking over all the changes between FILES 434 and FILES 435, it seems version 434 is more correct in all cases.  I think all we need to do is revert FILES 435 to FILES 434. I wonder what the provenance of FILES 435 is and whether there is anything "good" in it.  I kind of doubt it.

**Comment by larsbrinkhoff** [comment]
Great, thanks for fixing this.  FILES 435 was added here: #1520.
Consider this: "I'm going to create a FILES 435 to contain the fix to
Write File."

**Comment by eswenson1** [comment]
Since I created FILES 435, I’m going to compare the Write File version in PAT162 and see how differ. PAT162 seems to work with Emacs 162. When I run it, I don’t have the illegal flag error in mini buffer interactions.

**Comment by eswenson1** [comment]
See #1773 for a new ticket to update to FILES 440 (with fixes to damage in the file from its vault).
