### ISSUE TITLE
No source for LIBLSP;STRUCT *

### ISSUE THREAD

**Issue by BobKerns** [PDP-10/its#1800]
It's referenced by TEACH;ERRHEL >, but no source by that name exists.

LIBLSP;STRUCT FASL exists. L;STRUCT > is low-level MIDAS code for the interpreter.

Is there a more complete place I could dig for these? Another branch? I was never able to get my hands on the backup tapes nor Alan Bawden's sanitized versions, or KLH's starter ITS filesystem, nor...

Too late on all counts.

**Comment by BobKerns** [comment]
After looking at the FASL file in Emacs, I'm pondering just doing a native implementation. It would facilitate foreign-function interfacing.

It uses hunks, but I'm not seeing much utility in using them. Their design was dictated by Lisp's constraints on address space and how the GC worked.

STRUCT's have been implemented a gadzillion of times, but I think I know roughly what this one was.

**Comment by BobKerns** [comment]
Correction; TEACH;ERRHAN >, not TEACH;ERRHEL >.  The latter loads successfully.

**Comment by eswenson1** [comment]
What source file are you looking for, Bob?

**Comment by larsbrinkhoff** [comment]
> Is there a more complete place I could dig for these?

Probably not.  We put all the latest sources in this repository as soon as we can.

Bawden's and Harrenstien's sanitized versions are both based on the final backup that was made in 1990.  But at that point many files had went missing.  Due to the grim file reaper I guess.  Also some things may have been lost in the transition from KA10 to KS10 machines.

@eswenson1 and I have already extracted almost everything interesting from the 1990 snapshot and put it here.  Further additions have been facilitated by @lisper with some kind of approval from an educational institute, which has an incomplete archive of tape backups going back to 1972.

This repository only has the latest version of all files, but the repository http://github.com/PDP-10/its-vault has a more complete coverage.  Possibly some files are in "its-vault" that we haven't yet moved to "its".

**Comment by BobKerns** [comment]
OK, thanks.  How do you manage changes/fixes from that baseline? Should pull requests bump the version number? Remain on a branch separate from master?

As for LSPLIB;STRUCT FASL, after peering at the FASL file and grepping around the repo, I think it was likely built from ALAN;NSTRUC 280. There's also an ALAN;NSTRUC 291, but the FASL file contained the version '280', which seems a strong coincidence despite the differing filenames.

I always disliked the idea of keeping shared sources in personal directories, because, well, this....except I did it for the password stuff just to make it a bit less obvious.

I remapped it to ALAN;NSTRUC 280 and am working on making it load which so far has entailed multiple values and the need for better control over the run state (e.g. abort,  pause for debugging, etc.)

**Comment by eswenson1** [comment]
I had found NSTRUC 291, but when I tried the build the system with it, I had issues. I checked the latest FASL file from MC and saw that it had been compiled from NSTRUC 280 and therefore reverted the NSTRUC included in the build to that version.

**Comment by eswenson1** [comment]
Also, if you look at the file build/lisp.tcl you can see what sources were used to compile the corresponding FASLs.

**Comment by BobKerns** [comment]
Ah, that should save me a lot of hunting around; I can put that into my list of aliases directly. Thanks!

**Comment by larsbrinkhoff** [comment]
> How do you manage changes/fixes from that baseline? Should pull
> requests bump the version number?

Yes, we bump version numbers.

> I always disliked the idea of keeping shared sources in personal
> directories

There's a tension between making a cleaned-up "better" ITS, and keeping
most of the historical flair.  I tend to want to keep things close to
how they were back in the days.  But we're not always consistent with
that.

Also, what this repository builds is kind of a Frankenstein's ITS.  It
superimposes files from all ITS machines, from all time periods.  So in
that sense, it's not historically accurate at all.

(Really, we'd need a sliding scale to set the year and build an ITS
mathing that date...)
