### ISSUE TITLE
Unix more command

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#1900]
@dhalbert [wrote to comp.society.folklore](https://groups.google.com/d/msg/comp.society.folklore/f1TFS2XJG9s/lJT8SLJ5mcQJ) \<CM5AGo.28z@world.std.com>:

> I was a first-year graduate student at UC Berkeley in 1978. I had been an undergraduate at MIT, and had used the ITS timesharing systems there, which ran on PDP-10's. ITS put a "--MORE--" at the bottom of the screen when one typed out files; you pressed the space bar to continue.
> 
> At Berkeley, we'd just gotten our first VAX UNIX system, though there were already PDP-11 UNIX systems.  There was a very simple program through which one could pipe stdout to do screen-at-a-time output. It rang the terminal bell after printing 24 lines, and waited for a carriage return. It was called "cr3". My guess is that in some version of UNIX, someone had hacked a page-at-a-time output mode into the tty output drivers.  Using stty, one could already say "cr0", "cr1", and "cr2", which added different amounts of delay when printing a carriage return, for the benefit of slow printing terminals. "cr3" was probably unused, and the page-at-a-time mode was piggybacked on it. But our version of UNIX didn't have this "cr3" stty mode; instead we had the "cr3" program that provided equivalent functionality.
> 
> Many of the terminals at Berkeley were Lear-Siegler ADM-3 and ADM-3A "dumb" terminals. Both models (or maybe just the ADM-3 - I don't remember) rang the terminal bell when the cursor advanced to near the right margin, as a typewriter bell would. Unfortunately, they rang the bell on output as well as keyboard input, which made for incessant beeping.  It was particularly maddening in a room full of terminals. So most of the bell speakers had been disconnected.
> 
> Since "cr3" rang the terminal bell to indicate that a full page had been output, you couldn't tell when it was waiting for input on those muted terminals.  The problem was exacerbated by the slow response time of the overloaded UNIX systems.
> 
> So I wrote a simple "cr3"-like program, but had it print "--More--" instead of ringing the bell. I had it accept space instead of carriage return to continue, because that was what I was used to from ITS. I also made it take multiple filenames, and had it print lines of colons ("::::::::::::") before and after it printed each filename.
> 
> I named the program "more". This was a daring move at the time, since it was such a long name for a UNIX command, and was also a real English word.
> 
> Subsequently, my friends and fellow graduate students Eric Shienbrood and Geoff Peck greatly expanded the program, adding all kinds of command line options and different possible responses to the "--More--" prompt. It was of course distributed in the BSD versions of UNIX.
> 
> Some time later, Don Norman wrote an article for Datamation entitled "The Trouble with UNIX", in which he complained, among other things, about the cryptic nature of most UNIX command names, citing "more" as an example.  I never did tell him that I thought "more" was a great improvement over "cr3".
> 
> I was later amused to see "more" appear in MS-DOS (and perhaps even before, in CP/M?).
> 
> Dan Halbert

**Comment by dhalbert** [comment]
My account above is also available at https://danhalbert.org/more.html, and is linked from https://en.wikipedia.org/wiki/More_(command).

**Comment by larsbrinkhoff** [comment]
Thank you, Dan.

There is some discussion about more/less/pg etc on The Unix Heritage Society mailing list.  There is a claim Eric Shienbrood started fresh with a new version of more, which is counter to your account.  Do you have any recollection if Eric started a new program at some point?

**Comment by dhalbert** [comment]
Thanks - I asked to join the list, but haven't been added yet. Could you reply for me, for now, with the following?

---

As described in https://danhalbert.org/more.html, I wrote the original version of `more`. It was only a page or two or code, and was meant to replace the dysfunctional `cr3`. It went into raw mode so it could read a space as a "next page" character, but otherwise didn't care about what kind of terminal it was on. (The ADM-3's (not 3A's) were barely a terminal.)

Clem Cole's timeline is a bit off. Eric Shienbrood, Geoff Peck, and I all arrived at Berkeley at the same time in fall 1978 as CS grad students, and became friends (along with some other folks).

After I wrote the first version, I did not have time to continue to working on it, so Eric picked it up and added many more features. My contribution is that I had the original idea (to replace `cr3`) and coined the name, and made the very first version. I am grateful to Eric, Geoff, and others taking it much further with many more features.

I am still in touch with Eric, and will ask him to see what he has to say. We are both  still alive so I appreciate Lars getting in touch with me to verify.

I also wrote a hack `less` as a joke, which was `more` except that it scrolled up the screen rather than down . I think it was Bill Joy who then wrote another `less` that paged from the end of the file (and also scrolled up the screen).

**Comment by larsbrinkhoff** [comment]
Thanks!  I posted your message to the list.

**Comment by larsbrinkhoff** [comment]
For the record, it's here: https://minnie.tuhs.org/pipermail/tuhs/2020-June/021475.html

I'm hoping we will get to see Eric's point of view on this.
