### ISSUE TITLE
LISP vs Assembly Example on PDP-6 or PDP-10?

### ISSUE THREAD

**Issue by stephencwelch** [PDP-10/its#2035]
Hello! Alright, I know I keep popping up with issues - feel free to close if I get off topic. 

As I mentioned elsewhere, I'm working on some research for my YouTube channel [Welch Labs](https://www.youtube.com/channel/UConVfxXodg78Tzh5nNu85Ew). I'm trying to present a clear explanation of high level programming languages like LISP vs assembly language. What I would love to show is an example of a couple LISP operations, and their equivalent in assembly. 

Are there any places I could look for for such examples? Or, if I want to get hardcore, can I compile some LISP operations myself? If I understand [AIM-039](ftp://publications.ai.mit.edu/ai-publications/pdf/AIM-039.pdf) correctly, the LISP compiler on the PDP-6 compiled directly to machine code, not assembly, so I'm guessing my options may be a little limited there. 

Any pointers to relevant documents/resources is much appreciated!

**Comment by aap** [comment]
The PDP-6 LISP compiler produced assembly in LAP (lisp assembly program) format (i.e. S-expressions), which was then assembled to machine code by some other LISP code. I don't think either of those have survived for the PDP-6, but they should be in later MacLISP somewhere. I think there's an example of LAP code somewhere but i don't remember where exactly.

**Comment by larsbrinkhoff** [comment]
Hello.  Just a quick note for now, but I find this very interesting.

PDP-6 and Maclisp kind of defies the regular view of Lisp and a high-level language, and conversely PDP-6/10 assembly language programing can be more high level and dynamic than we are used to think.  E.g. writing and modifying machine code in DDT is a kind of image-based development, a concept normally reserved for languages like Lisp and Smalltalk.

**Comment by larsbrinkhoff** [comment]
Given the right declarations, the Maclisp compiler will get quite close to generating a single instruction for a PLUS call.  I will provide an example later.

And Yes, you can test all this yourself on ITS.  Either building this repository, or more conveniently logging in to an online machine.

**Comment by larsbrinkhoff** [comment]
Maclisp has the special fixnum `+` operator, so this:

```
(defun add (x y)
  (+ x y))
```

Turns into this:

```
0/   DMOVEM 15,635413(1)   
1/   MOVNM 12,@121(4)   
2/   HRLO 60277   
3/   1   
4/   ANDM 2,400000(10)   
5/   1   
6/   HRLZM 12,@251000(10)   
7/   MOVE 7,(1)   
10/   ADD 7,(2)   
11/   JSP 6,   
12/   23   
13/   POPJ 14,   
14/   1,,2   
15/   3,,0   
16/   DMOVEM 15,635413(1)   
```

I don't know what all this is, but probably the ADD code is 7-12: fetch one operand, add the other, and return.

**Comment by stephencwelch** [comment]
Wow, @larsbrinkhoff - this is great! Did you generate that example? I'll have a look at building myself this weekend. 

I know LISP has dynamic typing, I'm curious where compiler uses the type of `x` and `y`. I also see in the [LISP 1.5 Programmer's Manual](http://www.softwarepreservation.org/projects/LISP/book/LISP%201.5%20Programmers%20Manual.pdf) that LISP supports arrays as well - I'm wondering what an array example would look like.

**Comment by larsbrinkhoff** [comment]
@stephencwelch, sorry I forgot to answer you.

Yes, I generated that.  I entered the Lisp code into a file (test lisp), and then ran the COMPLR program to compile it.  Like this:

```
*:complr
LISP COMPILER 2000 [in LISP 2154]
_test lisp
_^Z
*:kill
```

I typed `test lisp` at the `_` prompt.  When the prompt appears again, type `^Z` and then `:kill` to exit the compiler.

In this case, the compiler avoids dynamic typing due to the use of the `+` operator.

**Comment by swelchm** [comment]
Great, thanks @larsbrinkhoff - I spent a little setting things up on a VM, but haven't made it quite this far yet. This is a great resource, I'll pick back up on this when I have some bandwidth, please feel free to close this issue if appropriate.

**Comment by BobKerns** [comment]
Yeah, really, the '+' operation is just the ADD instruction. The MOVE is picking up one of the arguments, just as you would in assembly.  If it was the result of a prior computation, it might already be in a register and not need the MOVE. The JSP should be regarded as returning from the subroutine.

I don't know what the rest of it is.  It doesn't even look executable. It might be part of the FASL file format, instructions to the loader? I've dealt with too many formats since then to have any recollection of the MACLISP FASL format. Or much of the instruction set, for that matter, even though the PDP-10 is the last system I routinely wrote assembler for!

A more illustrative example might be:

(defun add (x y)
  (+  (+ x y) (+ x y)))
  
 I doubt it would optimize it into 2 ADDs rather than 3, but I wouldn't rule it out. But either way, it'll make clear what's overhead and what isn't, and give a bit of insight into register handling.
