### ISSUE TITLE
Idle ITS repeatedly complains about CHANNA 

### ISSUE THREAD

**Issue by oilcan-productions** [PDP-10/its#2116]
On my ITS system when it sits idle for a while the DRAGON daemon starts outputting the following two lines over and over amongst the GCBULK and DIGEST lines that are already know
```
PFTHMG DRAGON CHANNA _DRGN_ TIMES  WRITE  05:26:41
PFTHMG DRAGON CHANNA LOGOUT TIMES  DELRNM 05:26:41
PFTHMG DRAGON CHANNA _DRGN_ TIMES  WRITE  05:50:47
PFTHMG DRAGON CHANNA LOGOUT TIMES  DELRNM 05:50:47
PFTHMG DRAGON CHANNA _DRGN_ TIMES  WRITE  06:14:53
PFTHMG DRAGON CHANNA LOGOUT TIMES  DELRNM 06:14:53
PFTHMG DRAGON CHANNA _DRGN_ TIMES  WRITE  06:38:59
PFTHMG DRAGON CHANNA LOGOUT TIMES  DELRNM 06:38:59
PFTHMG DRAGON CHANNA _DRGN_ TIMES  WRITE  07:03:05
PFTHMG DRAGON CHANNA LOGOUT TIMES  DELRNM 07:03:05
```

Anything I can do to reduce the noise?

**Comment by larsbrinkhoff** [comment]
What you are watching is the system console, in effect the system log, so some noise is to be expected.  You should probably to log in on another terminal line for normal interactions.

The lines are due to activity from "Puff the Magic Dragon", which record accounting information for the system.  I'm not sure how often it updates the LOGOUT TIMES file.  If it really bothers you, you can simply kill the job with no great loss of functionality.  The accounting information was used to produce monthly reports, which were probably discarded or at least disregarded.  The same goes for GCBULK and DIGEST.

**Comment by oilcan-productions** [comment]
Thanks for the insight. I am using another console to login. Just wanted to see if I could get my system console cleaner :)
