### ISSUE TITLE
MINITS can't route outside local subnet?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#2119]
It seems MINITS can only make connections to hosts on the same subnet.

CC @eswenson1, @bictorv

**Comment by larsbrinkhoff** [comment]
MINITS can also be configured as a router, so supposedly it must be able to forward packets between different subnets.

**Comment by bictorv** [comment]
I had a quick look. Since MINITS connects to cbridge using UDP (i.e. point-to-point, so to speak), I think cbridge sends RUT packets addressed at the MINITS host (i.e. non-zero dest), but MINITS checks for the dest being zero (see cprrut in chsncp). 

This means MINITS doesn't use the RUT data, and thus its routing table will be empty, and only knowing how to send pkts to the local subnet.

I'm not sure how easy it is to fix the cbridge end, but certainly doable. Perhaps not today. You can try removing the check in MINITS and see if it helps, of course.

**Comment by bictorv** [comment]
You can try the rut-broadcast-fix branch of cbridge and see if it helps/works. It's running on MX12 now.

**Comment by larsbrinkhoff** [comment]
I tested the branch.  Can confirm, my MINITS can now reach both UP (on the same subnet) and ES (another subnet).  @eswenson1 also saw the improvement.

**Comment by bictorv** [comment]
Great! Since the bug wasn't even in MINITS, I suggest we close this.
