### ISSUE TITLE
COMSAT should default BUGHST to the local ITS

### ISSUE THREAD

**Issue by bictorv** [PDP-10/its#2331]
BUGHST in COMSAT is used as destination for mail to "BUG type recipients" which have no explicit entry in .MAIL.;NAMES. The default is `HN$MC`, i.e. MC.LCS.MIT.EDU at Chaosnet address 3131 (not in use on the global Chaosnet).

The build process sets BUGHST to the local ITS address, to keep things local. However, if your IP/Chaos address changes, you must remember to patch COMSAT with the new address, otherwise BUG email will be sent to the old address.

A simplification would be to let BUGHST default to 0, and change the code in RXPBUG to check for 0 and then use the local host address instead. (Currently it checks only if BUGHST is the local address or not.)

Thoughts?

**Comment by eswenson1** [comment]
I like that solution. I had thought that BUGHST had to match IMPUS3, so that is for the clarification. Since there is already logic to look up the local machine address in the host table, I think it would be perfect to use that value for BUGHST if it isn’t set.

There is still the issue of TCPGAT and DOMGAT needing to be set properly if external mail is to be delivered though. Those have to be updated unless we did something similar — using fixed aliases in the host table and having COMSAT look them up if their values are 0.

**Comment by bictorv** [comment]
Thanks! This could be combined with #2332 using something like

`(*COMSAT-BUGHOST (R-NAME some-other-machine))`

if you some day want something else than the local host.

**Comment by eswenson1** [comment]
Yes. Agreed.
