### ISSUE TITLE
inquir has a non-free license; also: project policies

### ISSUE THREAD

**Issue by 36bit** [PDP-10/its#258]
I noticed that inquir has a [proprietary software](https://www.gnu.org/philosophy/free-sw.html) license on it. I wonder if anyone has contacted MIT about changing this? But then that got me wondering: Is that even a goal for this project? As in, does it matter to this project whether or not members of the public are actually able to use, modify, and redistribute ITS [in freedom](https://www.gnu.org/philosophy/freedom-or-power.en.html)? At present that's not clear to me so I find myself wondering what the mission and policies of this project actually are. There doesn't seem to be anything stated anywhere. Clearly the mission seems to be to resurrect ITS, but under what conditions? Is it like:
> Resurrect ITS at any cost, even if it is proprietary.

Or is it more like:

> Resurrect ITS, but only if it's [free software](https://www.gnu.org/philosophy/free-sw.html).

I would not be interested in helping with the former but I could be interested in helping with the latter. But only if that is actually part of this project's overall mission and policies which, as I've said, I don't have a clue on (and I don't want to impose my own thing on the project). It would be good to know what the mission and policies are, because knowing this is kinda fundamental to knowing if I want to continue helping or not.

**Comment by larsbrinkhoff** [comment]
I understand your concern.  I have my thoughts about this, but I'm not sure they should be on public record.

**Comment by larsbrinkhoff** [comment]
Regarding INQUIR, you may want to send a note to @cstacy, since he wrote it.

https://github.com/PDP-10/its/blob/master/src/inquir/inquir.182#L4

**Comment by cstacy** [comment]
I don't know what licenses are currently on the ITS source code, in general.
That's the first question I would have!

**Comment by 36bit** [comment]
> I don't know what licenses are currently on the ITS source code, in general.
That's the first question I would have!

From my initial and very rough review seems It seems a hodgepodge. MIT released (some) of ITS under the GPL. Still others parts are free of copyright restrictions and in the public domain (in the U.S.) because they were not published with a copyright notice, which was a requirement of U.S. copyright law at that time (it's not anymore, but that it used to be works to our advantage in this case.) Still others have various other licenses (like INQUIR) which are almost but not quite [free software](https://www.gnu.org/philosophy/free-sw.html).

**Comment by cstacy** [comment]
Yeah, it might even be worse than that, because exactly what material was (term of art) "published" at what time could be very complicated. (And there might even be material which didn't belong to MIT.) However, it is extraordinarily unlikely that MIT will ever come after anyone for doing anything with ITS.

Although ITS (when it only ran on five computers) was used by people doing commercial and proprietary work, the system itself was never a product and was never distributed. (By the way, this fact probably negates the idea that it was "published" during the pre-Berne USA Copyright era.) Anyway, ITS has never been considered to be an IP asset back in the day, and I really don't think any modern day MIT lawyers are going to come looking for trouble about it today.

So: legally, very murky.
Reality: hack away and have fun and absolutely *whatever*.

If MIT did an ITS release with GPL (where is that document?) it certainly indicates their modern intentions with regard to the IP. I would not worry about other MIT Copyright notices that conflict with the GPL license distribution authorization (even though I've never seen it).

Definitively clearing up all Copyright issues on any files that might be part of ITS would probably be very difficult and expensive and unlikely to get done. The only thing I'd worry about is files that might seem to be part of some ITS distribution, but which were not really part of ITS (e.g. not MIT's IP).

INQUIR is part of ITS.
I assure you that the libraries it uses are also not a problem, either.

**Comment by 36bit** [comment]
> However, it is extraordinarily unlikely that MIT will ever come after anyone for doing anything with ITS.

I also think this but will still do my due diligence here. And it's not that the license of INQUIR prohibits distribution (it does allow it.) So the project isn't running afoul of MIT copyright by having it. It just falls short of the free software definition, which is the part I'm hoping to change.

> If MIT did an ITS release with GPL (where is that document?)

The GPLed stuff from MIT can be found at http://groups.csail.mit.edu/mac/ftpdir/its/
It's specifically under GPLv2-or-any-later-version, which makes upgrading to v3 very simple.

> And there might even be material which didn't belong to MIT

There may very well be other stuff that does not belong to MIT, given that they seemed to have a somewhat open access policy for ITS. This doesn't necessarily make things any worse; it actually helps. If someone outside MIT was submitting stuff to the folks at MIT for inclusion into ITS that certainly counts as publishing their work, since it allowed other people (besides the individual that made the program) to get copies of the software on the computers at MIT, since they themselves put/sent it there for people to use.

The open access policy also helps with stuff also helps with stuff written directly by MIT staff and installed on the system. People outside of MIT would have had the same access to those programs on the machine.

In both cases the lack of notice then works in our favor in the pre-Berne era.

**Comment by cstacy** [comment]
I disagree with your legal analysis.

**Comment by atsampson** [comment]
> If MIT did an ITS release with GPL (where is that document?)

The MIT release, which I remember downloading enthusiastically in 1999, is at http://web.archive.org/web/20010920052418/http://www.swiss.ai.mit.edu:80/ftpdir/its/ - it's only the SYSDOC and SYSTEM directories, i.e. not enough to build a complete system, and is GPL v2 or later. I would love to see MIT extend this permission to cover more of ITS; at least, the parts that were written by their staff and students.

Other free software releases of peripherally-ITS-related material that I'm aware of:

- Brad Parker has a collection of CADR-related files from ITS which MIT released under an X11-style license: http://www.unlambda.com/index.php?n=Main.Mit - this is mostly SUDS and Lisp source for the CADR, but there are a handful of other files in MOON;.

- MIT and Bull released the Multics source under a custom (OSI-approved) license: http://web.mit.edu/multics-history/ - which includes the Multics versions of MacLisp, TECO, Emacs, etc. Not the same codebases as the ITS versions, but perhaps an argument could be made to MIT that they've already released a different platform's version...

- ESTSC agreed to release DOE-MACSYMA under the GPL in 1998: http://maxima.sourceforge.net/ - which is a distant descendant of the ITS version.

- The GNU Emacs manual is derived from the ITS Emacs manual - more obviously so in older versions, but there are chunks of text that still survive today.

**Comment by larsbrinkhoff** [comment]
This is my copy from back then:  
http://pdp10.nocrew.org/its/swiss/

**Comment by larsbrinkhoff** [comment]
I don't think there's much horse left to beat here.
