### ISSUE TITLE
Dungeon/Zork (Supnik) - game

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#421]
This is the @archivisth Fortran rewrite of Zork.

Source code: http://simh.trailing-edge.com/games/dungeon.zip  
Need Fortran, see #170.

https://en.wikipedia.org/wiki/Zork#Fortran_port

![](https://upload.wikimedia.org/wikipedia/commons/4/44/4.3_BSD_UWisc_VAX_Emulation_Zork_Intro.png)

**Comment by atsampson** [comment]
What directory would this go in - SUPNIK? (RMS is obviously already in use...)

**Comment by eswenson1** [comment]
I recommend the games; directory.  So this is the Fortran port of Dungeon?  What version?

**Comment by larsbrinkhoff** [comment]
Text files in the zip mention V3.2B and the date December 9th 1994.  It probably corresponds to the very last Muddle version, since Supnik says the Zork imps gave that to him.

I don't know about points.

**Comment by larsbrinkhoff** [comment]
It also says "Sources changes for V3.2B of Dungeon after release".  Does that mean there were updates after 3.2B was released.  You should probably diff against the Multics version to check you have the latest and greatest.

**Comment by eswenson1** [comment]
Yes, that's the 616/100 point version. That's great.  I tried (unsuccessfully) to compile this for ITS (even though we were able to compile this for Multics) and I'm curious whether you (or anyone) has attempted this yet (and been successful)?

**Comment by larsbrinkhoff** [comment]
I haven't even attempted.  Maybe the F40 compiler isn't good enough.

**Comment by eswenson1** [comment]
As soon as we got this running on Multics, I played through the whole thing (including endgame) to "QA" it.  Testing can be fun!  It worked.  Here are the last few lines of output:

```
   As you gleefully examine your new-found riches, the Dungeon
Master himself materializes beside you and says, "Now that you have
solved all the mysteries of the dungeon, it is time for you to assume
your rightfully-earned place in the scheme of things.  Long have I
waited for one capable of releasing me from my burden!"  He taps you
lightly on the head with his staff, mumbling a few well-chosen spells,
and you feel yourself changing, growing older and more stooped.  For
a moment there are two identical mages staring at each other among
the treasures, then you watch as your counterpart dissolves into a
mist and disappears, a sardonic grin on his face.

PAUSE --More-- at rooms$rappli|4365
(>udd>sa>ejs>mdungeon>bound_dungeon)
r 13:03 0.165 0 level 2

sr
Your score in the endgame is 100 [total of 100 points], in  751 moves.
This gives you the rank of Dungeon Master.

STOP via call exit
r 13:04 0.071 0
```

Turns out the PAUSE function causes a break to command level.  So I had to restart the program after the break (like a ^Z) to make sure I had really won!

**Comment by larsbrinkhoff** [comment]
I'm looking to try this for [VCF Zurich](http://vcfe.ch).

> What directory would this go in - SUPNIK?

> I recommend the games; directory. 

It's around 20 files, which I think is too many to clutter GAMES.  (Maybe do some kind of split similar to EMACS/EMACS1?  GAMENG for source code?)

DUNGEON is one character too long.  SUPNIK would be OK.  We do have ZORK for the MDL version, but maybe that should be renamed CFS.

I wonder what user name @archivisth used on DM ITS?

**Comment by larsbrinkhoff** [comment]
> I'm curious whether you (or anyone) has attempted this yet (and been successful)?

I did try now, and I was not successful.  The F40 compiler only supports Fortran 66 syntax, but Dungeon uses e.g. `INCLUDE` and `!` comments that are not part of Fortran 66.

**Comment by larsbrinkhoff** [comment]
There's an older version here: http://www.ibiblio.org/pub/academic/computer-science/history/pdp-11/rt/dsk/misc/dunsrc.dsk

**Comment by larsbrinkhoff** [comment]
Most files from the 1980 version compiles once ! comments are removed.  Some files elicit these kinds of errors:

```
********              OPEN (UNIT=1,NAME='DSAVE.DAT',ACCESS='SEQUENTIAL',
********                           ^
********             M-26 NOT A RECOGNIZED ARGUMENT TO OPEN/CLOSE
```

and

```
********              DATA R50MIN/1RA/
********                           ^
********             S-1 ILLEGAL NAME OR DELIMITER OR KEY CHARACTER
```

**Comment by larsbrinkhoff** [comment]
The DATA statements have Radix-50 constants of the form "*n*R*string*", where *n* is the number of characters.

**Comment by archivisth** [comment]
On http://simh.trailing-edge.com/software.html - final line has pointers to "Sources to three classic adventure games: Adventure (Colossal Cave), 1994 VMS version; Zork, final ITS version; and the Fortran translation, Dungeon, 1990 {actually 1994} VMS version." The sources for Dungeon are complete and up to date. The "changes after release" documents lists all changes made in the final days I worked on it, and they're all present in the source set.

Unlike the PDP11 version of Dungeon, where memory space was at a premium, the VMS version uses ordinary text strings instead of RAD50 strings. However, it makes heavy use of VMS Fortran-isms, such as .AND., .OR., and .XOR. working on integers rather than just booleans, and RMS-specific options in OPEN.

I no longer have the original PDP11 ports of Adventure and Dungeon, but they are available on http://www.ibiblio.org/pub/academic/computer-science/history/pdp-11/rt/decus11/, packages 110340 (Adventure) and 110370 (Dungeon).

**Comment by larsbrinkhoff** [comment]
Thank you, the 1980 DECUS files look like the ones I extracted from the floppy disk image.

I'd use the VMS version, but it has too many updates to agree with the Fortran IV compiler found on ITS.
