### ISSUE TITLE
XD - Display XGP file on a Knight TV

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#634]
SYS1; TS XD *or* SYS3; TS XD  
SYSEN2; XD 430  
.INFO.; XD ORDER *missing*
INFO; XD 4

Reads an XGP file and displays it on a TV.

Written by DLW.

**Comment by larsbrinkhoff** [comment]
INFO; XGP 24 has a chapter on how to use XD.

**Comment by larsbrinkhoff** [comment]
Seems to work.  Tried a scan file from a PLT, but that didn't go over well.  Probably just works with a subset of scan files such as those from TJ6.

CC @atsampson, you might be interested in this one.  Type ? for help.

**Comment by larsbrinkhoff** [comment]
You can test it, but it's not without problems.  When it's working fine, we'll add it to this repository.

Here are some files and instructions:  
http://lars.nocrew.org/its/tv11/

As for the 340, it's already added.  When you built for "sims" you get the simulated display and software for it.  However, much of the interesting software doesn't work yet.  It has improved a lot the last few weeks though.

I'm happy to help you get going with this if you like.

**Comment by larsbrinkhoff** [comment]
I have now tested XD with TJ6MEM.  But it's not working.  It just prints the file ASCII contents.

@atsampson, I'm not very comfortable with the typesetting pipeline.  I ran TJ6 to get an XGP file.  That shoud be it, right?  Or do I have to make an XGP scan file, and if so how?

**Comment by atsampson** [comment]
Looking at the code for SYSEN2; XD, you're correct: it wants an XGP character mode file like TJ6 produces (not an XGP scan file like SCNV produces). If you look at the file you're feeding into it, it should start with a bunch of headers -- ;TOPMAR, ;VSP, ;SKIP etc.

I haven't dug into XD to see how it should be rendering on the TV. It's a lot more complex than VERSA's XGP reader because it has four completely separate parsers, for the first/second pass through each line of XGP character mode input in normal and "mini-display" modes. Does it produce better-looking output if you press M to go into "mini-display" mode?

It probably wouldn't be too hard to add TV output to VERSA, thinking about it...

**Comment by larsbrinkhoff** [comment]
Yes, the file does have those kind of directives.  Still XD displays it verbatim.  Mini-display looks the same, only smaller text.  This would be a great program to have working!
