### ISSUE TITLE
Muddle

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#665]
Making notes here.

**Comment by larsbrinkhoff** [comment]
According to STINK files, these should be linked together:

- PURE
- SPECS
- CONST (not in MUDXXX STINK)
- LDGC
- UTILIT
- UUOH
- MUDEX
- MAPPUR
- CORE
- ATOMHK
- INTERR
- NFREE
- GCHACK
- READCH
- AGCMRK
- READER
- PRINT
- BUFMOD
- ARITH
- MAPS
- PRIMIT
- STBUIL
- EVAL
- DECL
- MAIN
- MUDSQU
- FOPEN
- PUTGET
- CREATE
- SAVE
- AGC
- AMSGC
- SECAGC
- INITM

**Comment by larsbrinkhoff** [comment]
There's also MUDITS.

And SECAGC says it's for multi sections.

**Comment by larsbrinkhoff** [comment]
UUOH:

```
UUOTBL+6        6        0.     1-039   .FATAL  Shadowing a pseudo-op
DSAVA1+1        566      0.     8-002   No END statement
        in IFE Starting at 7-362

**Comment by larsbrinkhoff** [comment]
MAPPUR:

```
FXUPGO+2        207      0.     4-682   No END statement
        in IFE Starting at 1-335

**Comment by larsbrinkhoff** [comment]
ATOMHK:

```
RLOOK1+11       1050     0.     6-054   NOATMS  Undefined

**Comment by larsbrinkhoff** [comment]
INTERR:

Lots of symbols undefined.

**Comment by larsbrinkhoff** [comment]
READCH:

```
CIMAGE+14       1207     0.    12-002   No END statement
        in IFE Starting at 11-447

**Comment by larsbrinkhoff** [comment]
EVAL:

**Comment by larsbrinkhoff** [comment]
MAIN:

```
                GL+0     3.    12-004   Symbol table full
Unterminated successful bracketed conditionals
The first was at 12-004 of file MAIN

**Comment by larsbrinkhoff** [comment]
FOPEN:

```
CHNRNM+16       2207     0.    27-171   CHNRM1  Undefined
GTINTC+10       4456     1.    39-017   Stray )
PTINTC+12       4505     1.    39-048   Stray )

**Comment by larsbrinkhoff** [comment]
SAVE:

```
FASTR1+5        176      0.     1-322   Externals multiplied

**Comment by larsbrinkhoff** [comment]
AMSGC:

```
CHNFLS+1        GL+533   0.    12-037
        Comma past the 3rd field of a word

**Comment by larsbrinkhoff** [comment]
SECAGC:

```
GCRD1+1         GL+1142  0.    25-016   Symbol table full

**Comment by larsbrinkhoff** [comment]
`.SYMTAB 3337.` fixes the symbol table errors.

**Comment by larsbrinkhoff** [comment]
@taa01776 We have found a TOPS-20 Muddle interpreter.

Now would be a good time to ask permission to release it.

**Comment by taa01776** [comment]
“Interpreter” meaning what files, exactly?
                -ta

**Comment by larsbrinkhoff** [comment]
> “Interpreter” meaning what files, exactly?

Here's the file list.  You can probably tell better than me exactly what it is.

```
agc.bin.16      fopen.bin.22    mdl106.sec.1      readch.mid.212
agc.bin.21      fopen.mid.35    mdl106.sec.2      readch.mid.213
agc.mid.131     fopen.mid.54    mdl106.sgc.1      readch.mid.214
agc.mid.139     fopen.mid.56    mdl106.sgc.2      reader.bin.10
agc.mid.140     fopen.mid.57    mdl106.symbols.1  reader.mid.353
agc.mid.141     fopen.mid.58    mdl106.symbols.2  reader.mid.355
agcmrk.bin.3    fopen.mid.59    mdlxxx.exe.1      reader.mid.356
agcmrk.mid.1    fopen.mid.60    mdlxxx.exe.2      reader.mid.357
amsgc.bin.12    fopen.mid.61    mdlxxx.symbols.1  save.bin.13
amsgc.mid.107   fopen.mid.62    midas.bin.3       save.bin.9
amsgc.mid.108   gcgdgl.mud.1    midas.exe.5       save.mid.169
amsgc.mid.109   gcgdgl.nbin.1   midas.symbols.2   save.mid.174
amsgc.mid.110   gcgld.mud.1     mud105.stink.10   save.mid.175
arith.bin.4     gchack.bin.2    muddle.mid.346    save.mid.176
arith.mid.94    gchack.bin.3    mudex.bin.34      secagc.bin.32
assem.all.7     gchack.mid.45   mudex.bin.38      secagc.mid.80
atomhk.bin.6    gchack.mid.46   mudex.mid.177     secagc.mid.81
atomhk.bin.7    initm.bin.17    mudex.mid.183     second.cmd.10
atomhk.mid.144  initm.mid.371   mudits.mcr130.1   specs.bin.7
atomhk.mid.149  initm.mid.373   mudits.mid.131    specs.mid.110
atomhk.mid.150  interr.bin.28   mudsqu.bin.6      specs.mid.111
bufmod.bin.2    interr.bin.30   mudsqu.mcr025.1   stbuil.bin.10
bufmod.mid.4    interr.mid.419  mudsqu.mid.28     stbuil.mid.15
chess.script.1  interr.mid.425  mudxxx.stink.2    stbuil.mid.16
chkdcl.mud.2    ipc.bin.2       mymode.teco.1     stbuil.mid.17
chkdcl.nbin.2   ipc.mid.19      nfopen.bin.2      stbuil.mid.18
_chkdcl.temp.1  ldgc.bin.11     nfopen.mid.4      stbuil.mid.19
_clr.ev.1       ldgc.mid.100    nfree.bin.5       stbuil.mid.20
_clr.opcodes.1  main.bin.9      nfree.mcr052.1    stenex.mid.11
_clr.opcodes.2  main.mid.350    nfree.mid.53      stink.exe.13
_clr.rmode.1    main.mid.351    oreadch.mid.208   stink.mid.1
const.bin.4     main.mid.352    primit.bin.5      stink.symbols.4
const.mid.5     mappur.bin.34   primit.mid.315    symbol.cmd.4
core.bin.4      mappur.bin.37   primit.mid.316    tmudv.bin.1
core.mid.13     mappur.mid.146  print.bin.11      tmudv.mid.1
create.bin.3    mappur.mid.159  print.bin.9       txpure.bin.2
create.mid.40   mappur.mid.160  print.mid.340     txpure.mid.3
decl.bin.3      mappur.mid.161  print.mid.346     utilit.bin.15
decl.mid.102    mappur.mid.162  pure.bin.5        utilit.bin.16
decl.mid.103    maps.bin.2      pure.mid.15       utilit.mid.103
ecagc.bin.1     maps.mid.29     putget.bin.3      utilit.mid.104
eval.bin.13     mdl106.agc.1    putget.mid.51     utilit.mid.105
eval.bin.14     mdl106.agc.2    pxcore.bin.2      uuoh.bin.23
eval.mid.122    mdl106.dec.1    pxcore.mid.9      uuoh.bin.25
eval.mid.123    mdl106.dec.2    readch.bin.12     uuoh.mid.179
eval.mid.124    mdl106.exe.2    readch.bin.16     uuoh.mid.181
eval.mid.125    mdl106.exe.3    readch.mid.206    uuoh.mid.182
first.cmd.2     mdl106.exe.4    readch.mid.210    uuoh.mid.183
fopen.bin.16    mdl106.exe.5    readch.mid.211    x.x.3

**Comment by taa01776** [comment]
Yup, that’s Tops-20 (obviously, because of the version numbers) old Muddle source. Where the heck did you find it?
                -ta

**Comment by larsbrinkhoff** [comment]
Updated files checked in here:  
https://github.com/PDP-10/muddle/tree/its/%3Cmdl.int%3E

**Comment by atsampson** [comment]
I had a further look at this last night, based on @larsbrinkhoff's work; here's my updated code: https://github.com/PDP-10/muddle/tree/ats/its

I've persuaded all the MIDAS files from the newer version to assemble with MIDAS 458. I've also fixed the included copy of STINK and tested that it works with a simple example. However, for any of the source files that .INSRTs MUDDLE >, loading the resulting REL into STINK fails:

```
*:stink
STINK.201

*MEVAL$L$$
bad format: symbol missing
Undefined Global Assignment 6056 VECLOC
Undefined Global Assignment 6056 SQULOC
Undefined Global Assignment 6056 TVLOC
Undefined Global Assignment 6056 VECTOP
Multiply Defined Global 7 *7UV
Multiply Defined Global 4 SQULOC
Multiply Defined Global 2 *2IX
Multiply Defined Global 4 TVLOC
Multiply Defined Global 15 VECLOC
Undefined Global Assignment 6056 VECTOP
Multiply Defined Global 7 *7UV
Multiply Defined Global 2 *2IX
Multiply Defined Global 4 TVLOC
[snip dozens of similar lines]
bad format: symbol missing
bad format: symbol undefined
bad format: symbol missing
bad format: symbol undefined
bad format: symbol undefined
Non-existent Memory
```

Both STINK 201 and the included STINK fail in the same way; the former has more readable error messages. Loading a file that doesn't use MUDDLE >, e.g. CONST, seems to be fine.

The symbols it's complaining about seem to be those that are used in LOC constructs in MUDDLE >'s macros. I wonder if something's bitrotted in MIDAS's RELOCA support - perhaps an older version of MIDAS would be worth trying? Alternatively, could we persuade MIDAS to build it in one hit by constructing a file that includes all the other sources (removing the RELOCAs and adjusting the .INSRTs)?

I've also done the same fixups for the 1973 version: https://github.com/PDP-10/muddle/tree/ats/its73
But this has exactly the same problem when loading the resulting files into STINK, and it looks like it's not complete; e.g. it's missing VCREAT (which is in the Twenex version) and DISPLY (which isn't).

There are two binaries in the 1973 version, TS MUDDLE and TS OMUDDL, neither of which seem to work right for simple examples. So even if we get it to link there may be more work ahead...

It looks like the source belongs in MUDSYS;, from the .INSRT in STINK.

**Comment by larsbrinkhoff** [comment]
I suspect both MIDAS and STINK were slightly modified by the DynaMod group.  See e.g. this:

https://github.com/larsbrinkhoff/its-archives/blob/master/dmcg/SYS.03.02.pdf

**Comment by atsampson** [comment]
Yes -- the copy of STINK in <mdl.int> has some DMCG/NODMCG conditionals which aren't in the standard version, although the DMCG stuff was disabled as found.

**Comment by atsampson** [comment]
Tried building everything with MIDAS 352; no difference. Although ATOMHK and MAIN use the XMOVEI instruction, which 352 doesn't know about, so that suggests they were built with a newer version...

... but what version could have understood the errors in CONST 5, with duplicate TERMINs and one misspelled as TERMIM? The version history in AI:INFO;MIDAS ARCHIV says MIDAS 217 introduced stricter checking for TERMINs.

**Comment by eswenson1** [comment]
@larsbrinkhoff Maybe we should recover all the versions of MIDAS that we can, and try them out to see if we can figure out which is the *right* version.  It may well be, however, that there were local modifications of MIDAS on DM that are not captured in any of the MC or AI backup tapes.  That would be a shame -- and surprising.

**Comment by larsbrinkhoff** [comment]
Eric, I did recover many versions.  See the lars/midas branch.  I have 108, 323, 352, 400, 412, 421, 433, 455.  I think there are more, but it's a decent selection.  There are also some TSRTNS versions.

**Comment by eswenson1** [comment]
Have we tried compiling muddle with all of these?  Are there more versions to recover that might help?  I'd like to think that DM-specific changes were merged with the other changes, but I guess it is possible that they had their own version....

**Comment by larsbrinkhoff** [comment]
I haven't.  My suspicion is that it's not an older version that's needed.

Another example is use of expressions that are resolved at link time.  I believe standard MIDAS and STINK only supports very simple expressions, whereas Muddle uses more complex.  SYS.03.02 describes some of these additional linker features.  I haven't cross checked in detail with MIDAS or STINK, though, so I could be wrong.

**Comment by larsbrinkhoff** [comment]
> Alternatively, could we persuade MIDAS to build it in one hit by constructing a file that includes all the other sources

Yes, that's an option I have considered.

> It looks like the source belongs in MUDSYS;

Thanks, I didn't notice that.  We only have tiny scraps of information from DM ITS.  There's a backup listing with these files:

```
MUDSYS MAIN   MCR317    18      1/27/77 17:59:27.5
MUDSYS MAIN   MCR318    18      1/28/77 10:10:21.5
MUDSYS MAPPUR MCR185    18      1/31/77 13:59:58.5
```

We recognize MAIN and MAPPUR.  Apparently the DynaMod fn2 naming convention with XXXNNN has appeared here.  There's also XXFILE MTA224 and GUNNER MTA381.  I don't know what MCR or MTA means.  Author names (Chris Reeve, Tim Anderson)?

**Comment by atsampson** [comment]
I've modified a copy of STINK (using JOTTO's neat printing macro!) to show details about the blocks, symbols and linker instructions it sees in its input. This makes it much clearer what's going on, since there's a very direct correspondence between what MIDAS sees in phase 2 and what gets written to the REL. So a bit more progress:

- When STINK says "bad format: symbol missing", what it means is that the MIDAS source contained an EXPUNGE for a symbol that didn't exist. I've fixed one instance of this (DOTYPS in MUDDLE >) but it looks like there are others. It also looks like recovering from this error might be messing up STINK 201's internal state somehow; the older STINK 1 didn't try to recover.

- I think the "Multiply Defined Global" messages for TVLOC etc. may be harmless. They are indeed defined multiple times, because the macros in MUDDLE redefine them to keep track of the list of definitions they're building up.

- The "Undefined Global Assignment" messages for TVLOC etc. are because these are redefined by the MUDDLE macros, but the initial definition is only in SPECS. So you have to load SPECS REL into STINK before you load anything else.

**Comment by larsbrinkhoff** [comment]
There are some files hinting at the build process.  assem.all isn't that useful; it just assembles all files.  

first and second.cmd are a interesting.  There's a little bit of DDT patching going on.

The .stink files specify a set of files, and an order between them.  SPECS is second.

Maybe SECAGC shouldn't be linked into the ITS binary, because it's for multi-section machines.  Or maybe it should; it could be that the multi-section code is inactive but other parts are used elsewhere.

**Comment by atsampson** [comment]
The code in STINK to recover from "bad format: symbol missing" is definitely wrong: it needs to read a second word from the input (PUSHJ P,RPB) like the successful path would do.

Fixing that in the old and new versions of STINK gets a bit further; you can load PURE and SPECS, and then whatever you load next causes STINK 201 to print "Non-existant Memory" (and STINK 1 to crash at UNTHR+2, which is the same thing).

After a lot of tracing through STINK (and assuming I'm following this correctly), this happens in response to a local symbol definition in the type 3 block that's produced by the .LNKOT directive in the END macro. The block has previously included a link request code for the same local symbol, which should point to a linked list of addresses that the real address of the symbol should be written into. When STINK sees the definition, it tries to works its way through the linked list, but runs into a nonsense pointer (and ends up trying to interpret a string constant as an address).

The pointer in the link request is to a location that's later inside the same type 3 block -- which hasn't been read into memory yet because we've not got that far... so this looks like MIDAS's fault.

**Comment by larsbrinkhoff** [comment]
I think it would be strange if the version of stink in the <mld.int> directory wouldn't be able to link the MDL executable.  So maybe it's a special version of MIDAS that we need.

What is .LNKOT in END trying to do that confuses MIDAS.  Would it be possible to do a workaround by rewriting the macro to do something else?

**Comment by atsampson** [comment]
I'm pretty convinced now that the older STINK isn't all that different from the current one in terms of what it supports - the biggest differences are in how it handles high-segment linking, because it has the boundary hardcoded at 400000 and modern STINK makes it configurable (but defaulting to 400000). The majority of the code is identical.

.LNKOT tells MIDAS to dump out all the STINK information that's been accumulated so far. It would otherwise do this at the end of compilation, so trying without it is on my to-do list, as is trying without the PURE/IMPURE stuff.

**Comment by atsampson** [comment]
I've now got most of the 1973 MUDDLE source to assemble with current MIDAS and load successfully into current STINK (provided you fix the "bad format" problem mentioned above): https://github.com/PDP-10/muddle/tree/ats/its73

But the NUPRM source turns into binary junk halfway through, so I haven't been able to assemble it, and the symbols it provides (at least) are missing at the end of the link process. This is the equivalent of PRIMIT in the <mdl.int> source, so it's not really something we can do without; it'd need to be reconstructed from some combination of the newer PRIMIT and the TS MUDDLE binary.

By instrumenting STINK further, I've found two different causes of the nonsense pointer problem above:

- With the 1973 source, I was initially using MIDAS 73. For most files, it was producing reasonable input to STINK, but for EVAL, MIDAS was producing link requests without the bit set that indicates that the address of the location to be updated should be relocated. Hence the bad pointer. MIDAS sets that bit (in LNKPRO) if it thinks the location of the symbol has been relocated; it was apparently getting confused by the junk after the END directive in that file, and removing it fixed it!

- With the <mdl.int> source, and current MIDAS, MIDAS emits reasonable-looking link requests, but STINK sometimes relocates the address in them incorrectly. There's a good example of this when MUDDLE first uses its SYSCAL macro: it defines a symbol as . with some data after it, and MIDAS emits a link request for that symbol with the right address in, but the relocated location that STINK saves in its symbol table (from THRDR's call to RELOCT) isn't where it actually put the following data.

**Comment by larsbrinkhoff** [comment]
Too bad NUPRM is damaged.

I don't know, but I believe the MUDDLE files didn't come from the DynaMod ITS machine.  It's possible that someone made a copy and tried to build it with MIDAS and/or STINK versions that couldn't quite cope.  Maybe that explains why TS MUDDLE doesn't work.  We don't know if TS MIDAS and TS STINK came along with the other files, or if they were put there later.

**Comment by atsampson** [comment]
"Where it actually put the following data" isn't where MUDDLE intended it to be. The MUDDLE > include file defines the PURE/IMPURE macros, which let it accumulate code/data starting from two different addresses. This relies on both MIDAS and STINK to track . and the relocation offset correctly.

I've written a simple testcase based on these macros - https://github.com/atsampson/its-tests/tree/master/stink - and tried it with every combination of MIDAS {73, 76, 77, 458} and STINK {"2" from <mdl.int>, 201}. Only MIDAS 73 produces the correct result (with both versions of STINK):

<table>
<tr>
<th>
MIDAS 73<br>
STINK 2/201
</th>
<th>
MIDAS 76/77<br>
STINK 2
</th>
<th>
MIDAS 76/77<br>
STINK 201
</th>
<th>
MIDAS 458<br>
STINK 2/201
</th>
</tr>

<tr>
<td>
100/ 1,,1<br>
101/ 1,,2<br>
102/ 1,,3<br>
103/ 1,,101<br>
104/ 1,,102<br>
105/ 1,,103<br>
106/ 1,,201<br>
107/ 1,,202<br>
110/ 1,,203<br>
700000/ 7,,1<br>
700001/ 7,,2<br>
700002/ 7,,3<br>
700003/ 7,,101<br>
700004/ 7,,102<br>
700005/ 7,,103<br>
700006/ 7,,201<br>
700007/ 7,,202<br>
700010/ 7,,203<br>
HI=700011 LO=111
</td>

<td>
100/ 1,,1<br>
101/ 1,,2<br>
102/ 1,,3<br>
103/ 1,,101<br>
104/ 1,,102<br>
105/ 1,,103<br>
106/ 1,,201<br>
107/ 1,,202<br>
110/ 1,,203<br>
700000/ 7,,101<br>
700001/ 7,,102<br>
700002/ 7,,103<br>
700003/ 7,,201<br>
700004/ 7,,202<br>
700005/ 7,,203<br>
HI=700006 LO=111
</td>

<td>
100/ 7,,101<br>
101/ 7,,102<br>
102/ 7,,103<br>
103/ 7,,201<br>
104/ 7,,202<br>
105/ 7,,203<br>
106/ 1,,201<br>
107/ 1,,202<br>
110/ 1,,203<br>
700000/ 7,,1<br>
700001/ 7,,2<br>
700002/ 7,,3<br>
HI=106 LO=111
</td>

<td>
100/ 1,,1<br>
101/ 1,,2<br>
102/ 1,,3<br>
103/ 1,,201<br>
104/ 1,,202<br>
105/ 1,,203<br>
700000/ 7,,1<br>
700001/ 7,,2<br>
700002/ 7,,3<br>
700003/ 7,,201<br>
700004/ 7,,202<br>
700005/ 7,,203<br>
HI=700003 LO=103
</td>
</tr>
</table>

Unfortunately, we only have a non-MOBY version of MIDAS 73, which can't handle several of the bigger files in the MUDDLE source. I've tried binary-patching it to have a larger symbol table but it's definitely non-trivial.

**Comment by eswenson1** [comment]
I can't find any source for MIDAS 73, but I do see sources for MIDAS 108 and 199.  I wonder if those would be useful to retrieve (and build moby versions for)?

**Comment by larsbrinkhoff** [comment]
Eric, we do have MIDAS 108.  It's in the PDP-10/its-vault repo.

I think I tried to retrieve 199, but it didn't work out.  We do have a binary for 135 if that's any help.

**Comment by eswenson1** [comment]
Ok, then @atsampson does it make sense to see if you can build a moby version of MIDAS 108 and see if that behaves as well (or better) than MIDAS 73?

**Comment by larsbrinkhoff** [comment]
I have assembled MIDAS 108 and it's MOBY by default.  I used 458 to assemble, and I don't think there were any particular problems.  Maybe add a few definitions.  Apparently older MIDASes had a bunch of device symbols predefined like TTY, PI, etc.

**Comment by atsampson** [comment]
I've just tried a MIDAS 108 built from the source we have, but it crashes while building the HILO2/HILO3 files in my testcase. I've also tried MIDAS 352 (source from SAILDART), which behaves the same as MIDAS 458.

**Comment by atsampson** [comment]
Tried MIDAS 289 (purified from MIDAS BIN289). That produces the correct result with STINK 2 but not with STINK 201!

**Comment by larsbrinkhoff** [comment]
Seems like a hit-and-miss thing (mostly miss).  Is 289 moby enough, or has an adjustable symbol table?

**Comment by atsampson** [comment]
MIDAS 289 does indeed have dynamic symbol table support; that was added in MIDAS 98 according to MIDAS ARCHIV. It can compile all of the <mdl.int> source with our fixes, and the resulting REL files get further in STINK than anything else I've tried so far. :-) It eventually fails in INITM when the .LOP .VALUE assertion in there fires, indicating the TVBASE table has overflowed. I've tried increasing TVLNT unsuccessfully but not looked into it any further yet.

MIDAS ARCHIV also says that in MIDAS 135, as part of adding .DECTWO support, "IT IS O.K. TO INTERSPERSE HIGH AND LOW SEGMENT CODE BY SAVING AND RESTORING THE TWO LOCATION COUNTERS". So perhaps it worked originally, then broke at some point, then was fixed when adding .DECTWO, then broke again later...

However, I've also had a look back at the original <mdl.int> files. There's a midas.exe in there in [TOPS-20 sharable save format](http://bitsavers.informatik.uni-stuttgart.de/pdf/dec/pdp10/TOPS20/V7/JSYS_REFERENCE.MEM.txt) - converting it with wfconv -au produces output that doesn't look quite right but does include the ASCIZ string "CORRECTION PLEASE.", which appears in the MIDAS 73 binary but not in 76 or later. So along with all the other evidence (BIN filenames in the STINK file, broken conditional blocks, STINK 1 not handling bad EXPUNG directives, no .SYMTAB directives in the source...) I'm pretty confident that <mdl.int> was being built with something close to MIDAS 73 rather than a later version.

**Comment by atsampson** [comment]
MIDAS 308, which we have source for, behaves the same as MIDAS 289.

**Comment by atsampson** [comment]
Not there yet, but closer. 

I'm pretty convinced that the failing test in INITM is buggy (testing >= rather than <=). [Using .LOP](https://github.com/atsampson/its-tests/blob/master/stink/dvalue.mid), I've had a look at the values it's testing, and they seem sensible, so I've fixed the assertion. (It's a linker-evaluated expression, so perhaps it never actually got evaluated correctly before, but I'm just guessing...)

All the MIDAS 323-compiled files now load into STINK 2. Useful commands at this point: `?` shows unresolved symbols, `-1?`shows unresolved symbols and the relocation chain for each, `S` shows resolved symbols.

Most of the unresolved symbols were further ITS/TENEX conditional problems. I've pushed fixes for these to [ats/its](https://github.com/PDP-10/muddle/tree/ats/its).

However, I'm now left with a set of unresolved symbols with names like "TO B$F" and "J$XGA7". Dropping some extra symbols into the source and looking at the output of -1?/S reveals that the locations STINK wants to write their values into are "between files" - i.e. adding a symbol at the end of MUDDLE's END macro and another at the beginning of the next file brackets the mystery addresses. So this looks like MIDAS doing something odd with REL output again, and the next step is to have a more careful look at the REL files.

**Comment by larsbrinkhoff** [comment]
Excellent work!  From the looks of your table, it seems like STINK "2" is the best bet so far.

I don't think it matters, but STINK 200 is a reconstruction from binary.  But done in the classic era:

> Date: Tue, 11 Jun 85 05:36:46 EDT
> From: Ken Harrenstien <KLH@MIT-MC.ARPA>
> Subject: STINK
> To: BUG-ITS@MIT-MC.ARPA
>
> You may find this news hard to believe.
>
> As you may recall, the source for STINK didn't assemble properly, and had a higher version number than the (presumably working) binary.  The true source, if it ever existed, has been lost in the distant fires of ITS dump tapes being burned at the stake.
>
> I was thinking about a possible hack which at some point might require the services of STINK.  Never mind what it is.  The problem as I saw it was not the fact that STINK is unique and unsupported, but the fact that STINK could not be supported without a real source.  So I made a half-hearted attempt to investigate by comparing the (faulty) result of an assembly with the existing binary, using SRCCOM's /$ switch.
> 
> Boy, am I glad I put that hack into SRCCOM.  The comparison much to my surprise showed the binaries were virtually identical, except for one changed label and a couple of missing symbols.  It only took a few minutes to fix those and come up with a source that assembles into exactly the same thing (modulo .FNAM2) as the old TS STINK!
> 
> Anyway, I wrote out this new source as STINK 200, and installed a new TS STINK.  STINK lives again!  (phew)

**Comment by larsbrinkhoff** [comment]
And let me add, that .LOP .VALUE trick is a delight!

**Comment by atsampson** [comment]
Second MIDAS bug found: it was writing out the symbol at the start of a CONSTANTS block in the wrong form. Here's [the fix to MIDAS](https://github.com/PDP-10/muddle/commit/8bfd9169aa0e4ec24cc41684c46b5f7efe1eb200) and [a testcase](https://github.com/atsampson/its-tests/blob/master/midas/const.mid).

With the versions of MIDAS and STINK in [ats/its](https://github.com/PDP-10/muddle/tree/ats/its), I can now successfully link a MUDDLE binary!

```
:mid289 ts m323f_midas 323
:midas ts msstk_stink 2
:xfile xfile muddle
(snip lots of output)
:msstk
MMUDDLE LOADER$@$$
(snip list of files)
*MMUDDLE BIN$Y$$
:KILL
*:job muddle
!
*:load muddle bin
*$g
.VAL 0; EBPUR1>>MOVEI 1,-1(5)   1/   IMAGFL+31   E.A. _ 1
```

This is about 110,000 instructions into its initialisation process, so it's making some progress at least! DDT doesn't seem to see all the symbols, although STINK can print a list of them with S$$. Single-stepping through the first few instructions fails because (in klh10, at least) it clobbers location 20, which MUDDLE wants to read early on, but setting a later breakpoint (SETUP+12) is OK.

I've had a look at the TOPS-20 build files from <mdl.int> and there doesn't seem to be anything particular they're doing in terms of purification - the two binary patches they apply are to set the version number (which VCREATE can do automatically on ITS, in theory) and to twiddle another parameter that doesn't apply to ITS.

**Comment by larsbrinkhoff** [comment]
Congratulations on getting this far!  It's a milestone.

**Comment by atsampson** [comment]
Success:

```
*:mudsav;muddle
MUDDLE
LISTENING-AT-LEVEL 1 PROCESS 1
<+ 3 4>$
7
```

So running the executable I built yesterday kicks off a purification process, which eventually drops you back into DDT to dump the real executable. I traced through the initialisation process, and fixed a number of problems:

- The crash I was seeing yesterday was because ILOOP, which copies objects into "pure" storage after the end of the code, was running off the end of memory. The pure section was configured to start at BOT=700000 and it looks like it's running about 2000 words over; I've set it to 600000 for now (as MUDDLE's comments indicate that used to be its value), but I guess you could get away with 670000 or similar.

- It should have printed `MUDDLE INITIALIZATION` by that point, and it hadn't. The syscall to open the TTY needed fixing (looks like a copy-and-paste error).

- `FATAL ERROR CAN'T CREATE SQUOZE FILE`. It expects the MUDSAV; directory to exist; it'll write various files there (e.g. the GC code, which it maps in when needed).

- `FATAL ERROR CANT FIXUP INTERPRETER`. The binary we've written so far needs to be MUDSAV;TS MUDG, in PDUMP format; MUDDLE opens the file and reads the page map out of it. So you can't use STINK's Y command, you have to drop into DDT with D and :pdump it. The MUDG name is derived from MUDDLE's version number, which should be written into MUDSTR before dumping, but it works without for now.

- `FATAL ERROR INITM -- CAN'T PURIFY HIGH CORE`. By this point it's written out its executables and tried swapping in the GC, so it's mostly working. This is the last CORBLK call in PURIMP failing, trying to make all the pure-code pages read-only. I don't know why it doesn't work (any ideas?) -- so I've commented it out... which gets it to the final valret happily.

I haven't tried anything more complex than arithmetic with MUDDLE yet, so it's quite likely more stuff is broken. All the changes above on the [ats/its](https://github.com/PDP-10/muddle/commits/ats/its) branch; it'd be helpful if someone else could try building it to check I've not left anything out.

I found another bug in MIDAS as well: using the JRST [stuff... ? JRST .+1] idiom for a skippable block doesn't work in RELOCATABLE mode, because it treats . as the location inside the constant. Fortunately MUDDLE doesn't use this!

**Comment by eswenson1** [comment]
Congrats! That’s great. Now it will be interesting to see if your assembles muddle does better than the executable we tried to run zork sources with!

**Comment by larsbrinkhoff** [comment]
Fantastic!

I'll verify that I can build this as well.

I'm eager to have this merged into the its repository.  I think we can use special versions of MIDAS and STINK.  (There's historical precedent.)  Long term, I'd like to make all necessary fixes to the latest versions.

**Comment by larsbrinkhoff** [comment]
One thing to test: garbage collection.  Ensure that the mult-section GC isn't used.

Also check whether SECAGC is needed at all in the ITS version.

**Comment by larsbrinkhoff** [comment]
MIDAS 323, STINK "2", and Muddle (to be 56?) are now built in the ats/muddle branch.

One strange thing is that STINK doesn't print its "*" prompt.

**Comment by larsbrinkhoff** [comment]
I did a quick test leaving out AMSGC REL from the link.  UTILIT wants IAMSGC, and LOADGC wants MARK2S and SLENGC.  No other undefined symbols.

**Comment by larsbrinkhoff** [comment]
Oops, that was the wrong garbage collector!

SECAGC is indeed not needed in ITS Muddle.

**Comment by larsbrinkhoff** [comment]
TENEX Muddle from June 1975: https://github.com/PDP-10/muddle/blob/master/sumex/
