### ISSUE TITLE
KLH10 build fails on Eric's VPS

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#743]
@eswenson1 has set up a VPS for running Jenkins.  Thanks!

However, it won't built ITS using KLH10.  It times out somewhere along the way with 100% processor usage (PDP-10 processor).

**Comment by eswenson1** [comment]
For the written record: Jenkins is not the issue. I cannot manually run the ITS build in a shell on this instance. The instance is running Ubuntu 14.04 LTS.  I have, successfully, built ITS on another Ubuntu 14.04 LTS VM, though, so there must be something specific about this environment.

**Comment by larsbrinkhoff** [comment]
I started a fresh build with newly cloned repos.  It timed out after building VV.

I have now increased the `type` delay between characters from .03 to .1 seconds.

**Comment by larsbrinkhoff** [comment]
lsb_release -a says it's Ubuntu 16.04.2 LTS, not 14.04.

**Comment by eswenson1** [comment]
Sorry, that's what I meant:  16.04 -- 16.04.02.  I'm so used to typing 14.04!

**Comment by eswenson1** [comment]
Yeah, that's where it first timed out for me.  I added a "sleep 2" before the expect check that followed that command, and got past it.  But then it failed again later on.  After putting in a few "sleep 2" commands in various places where I saw failures, it failed earlier in the expect script.  So that approach was not going to work.  Then, it started failing on the glob "?" match inside the type function.  When I removed that (as a test), I got past that.  The final failure was when expect send a ":midas xxxx\r" command to KLH10, and not only were the characters not echoed by ITS, but ITS did not appear to "see" that command.  I suspect KLH10 was hung at that point. 

Also, when I first tried the build with Jenkins, I would see KLH10 it close to 100% CPU usage.  It would usually eventually drop back down.  However, after the build was in progress for 2+ hours, I gave up and terminated the Jenkins job.  That's when I started seeing whether the build could run manually -- and noticed it didn't.

I wonder whether it would make a difference to TRY (just for debugging) KLH10 with networking disabled.  I wonder if the frequent hangs waiting for the network to come up are manifesting themselves differently in this environment -- and causing issues.  

Probably what we should do is see is a) increase the expect timeout (to allow easier debugging), b) wait until the expect script hangs (waiting for something that isn't going to happen due to the "issue" -- whatever it is), c) then check to see if KLH10 is running at close to 100% cpu utilization, and if so, interrupt the process and do a stack trace to see what it is doing.

**Comment by larsbrinkhoff** [comment]
Increased delay didn't work.  In a way, that's good.

**Comment by eswenson1** [comment]
Yeah, already tried that with an absurdly long delay (.9) and that didn't help at all.

**Comment by larsbrinkhoff** [comment]
fe_ctyin in fecmd.c clearly does get the characters fed from the build script, but somewhere along the way they get lost.

**Comment by larsbrinkhoff** [comment]
Trying with -DKLH10_CTYIO_INT=0.

**Comment by larsbrinkhoff** [comment]
Got stuck compressing EMACS libraries.  So no complete solution, but maybe it did alter something.  Hard to say.

**Comment by larsbrinkhoff** [comment]
Testing old machine with Ubuntu 17.10 / Linux 4.13.

**Comment by larsbrinkhoff** [comment]
That went fine.  So is it the software, or is there a problem with machines that are too fast?

**Comment by larsbrinkhoff** [comment]
Random thought.  Maybe some interrupt gets lost on the PDP-10 side if the time between them is too short.

**Comment by larsbrinkhoff** [comment]
Comments in KLH10 Makefiles suggest asynchronous real-time signals doesn't work well in Linux.  So that's also a concert.  I tried building with those off, but got a timeout in Emacs.  Maybe that's an improvement, and the Emacs thing is a different problem.

I'm feeling a bit exhausted about this and other problems.  I don't see a short-term solution.

**Comment by larsbrinkhoff** [comment]
The VPS has been closed down.
