### ISSUE TITLE
448-point adventure

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#798]
The 448-point adventure is referred to as advent 2 (II) in NGAME. It's executable is referenced by NGAME and the filename is specified when NGAME is assembled.  I have the sources and have successfully built this executable.

**Comment by eswenson1** [comment]
A couple questions:  Where should the executable go?  When you build NGAME, you have to tell it where the executable is.  So the executable could go anywhere.  The data file used by the game is burned into the executable just prior to pdumping it, so it basically lives where it was when it was built.  One possibility is to put the sources in GAMES; (this is where the original ADVENT source is, as well as JOTTO and WUMPUS). Historically, the sources were not available (they were encrypted in an archive in MC:EJS;).  The executable was in an archive in EJS; or BMT1;  Now, we don't have to hide the sources, so I recommend we put them either in EJS; or GAMES;.  The executable could go in SYS3; -- where we've put the original ADVENT, or it could go in EJS; or GAMES;.  One of the very confusing things is that we have three versions of ADVENT.  The sources for the original game are a single file (ADVENT.F4).  The sources for the 350-point version of advent are two files (ADVSB 2 and ADVSR 1) + the data file in ADVDB 1.  The sources for the 448-point version of advent are two files (MAIN 3 and SUBRS 16) + the data file in DB 2.  Creating the 448-point version renames the datafile (to FT01 DAT).  So if we put all of these sources in GAMES; it will be a bit confusing for people who are looking at it.  One possibility is to create three archives in GAMES; (or EJS;) AR1 ADVENT, AR2 ADV350, and AR3 ADV448).  We can put the sources and database in those archives.  We can then, during build, extract the files, build, and then delete them.  That way, there will be no confusion as to which sources go to which version.  

Now, the 350- and 448-point versions of ADVENT are referenced in NGAME by filenames that are entered at assembly time.  The other games locations are burned into the source (BMT1; or EJS;).  Should I keep them in their historical places or move them to GAMES;?

**Comment by larsbrinkhoff** [comment]
Some random thoughts.  Please discuss further.

- Where should the executabes go?

   I put the original ADVENT in SYS3, because there was such a TS ADVENT in the AI and MC snapshot.  It's most likely the wrong ADVENT, though!  Feel free to put the right version there if you like.

   I think the other executables should be in EJS or GAMES.  They can be plain files, or in an archive.  Since archives are so transparent in ITS, they are almost like subdirectories.  Since we have three ADVENT versions, one each could go in SYS3, EJS, and GAMES.  Bad idea maybe...

- Where should the source code go?

   I only created GAMES to have someplace to put games that didn't exist in the snapshots.  Now that we have EJS and BTM1, maybe that's the proper location.

   I personally don't think the confusion would be too bad if the files were all in the same directory.  But having them in three separate archives is fine too.

- Building from archives.

   We don't need to extract the files, do we?  Just build from the archives.  I see some historical binaries were built that way, so we can do that too.

**Comment by larsbrinkhoff** [comment]
I see SYS3; TS ADVENT was a short stub to tell people to use GAME.

**Comment by eswenson1** [comment]
Right. Back then, we wanted to make sure everyone used NGAME (GAME) rather than the games themselves. NGAME limited usage of games to certain hours and when the load was low and when there were free terminals.

**Comment by larsbrinkhoff** [comment]
I think this GAME menu is a good idea even now.  It makes it easy to find all games.  Maybe just lift the restrictions.

There's the matter of what to do with new games.  A few can be added to NGAME, but eventually we'd run out of letters.

**Comment by eswenson1** [comment]
I wonder if the Fortran compiler will let you specify sources from archives.  I seem to recall trying to specify a directory (as well as FN1.FN2) and this failed.  Maybe I did it wrong.  In any case, the build could extract the sources from the archive, compile them, and then delete them when it was done.  Do you know the syntax that DECSYS; F40 supports?  Is there any documentation on this compiler?

**Comment by larsbrinkhoff** [comment]
Oh, right.  No it may well not do that.  If you can specify a directory, it could be [dir]filename.  I think you can also say device:filename.

I think there's just this, but it's only the language.  http://bitsavers.org/pdf/dec/pdp10/TOPS10/DEC-10-AFC0-D_PDP-10_FORTRAN_IV_Programming_Manual_Aug69.pdf

@mattwyrm, do you know if there's a manual for the F40 compiler?

**Comment by larsbrinkhoff** [comment]
Also, filename translations.

If F40 tries to open, say GAMES; ADV448 F, you can add a translation to make it read, say, AR1: GAMES; ADV448 F.

**Comment by eswenson1** [comment]
Yeah. After reading your issue regarding subroutines in DDT, it occurred to me to do just that hack with DDT translations for advent compilation. May well do that.
