### ISSUE TITLE
ARDS display terminals

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#821]
ARDS was developed in-house at Project MAC.

This is the commercialized product:
![ards](https://user-images.githubusercontent.com/775050/40600925-680b7626-6253-11e8-8555-b1db27cd39f9.jpg)
![ards-display-terminal-1968](https://user-images.githubusercontent.com/775050/40600800-0b2fb912-6253-11e8-9885-af11bbfa3738.png)

**Comment by larsbrinkhoff** [comment]
.INFO.; ARDS INFO

**Comment by jh95468** [comment]
My recollection is that the ARDS (Advanced Remote Display Station) was developed by a group in building 20 at MIT, called something like "Electronic Systems".   I had a student job in 1968 or so building a teaching program on CTSS for use in a lab course in the Materials Science department.  Their ARDS connected to CTSS by dialup modem. 

Support for ARDSes on ITS was no doubt added at Project MAC, but the hardware was more widely used by CTSS customers.  At DM, we had several ARDSes which quickly became obsolete after Imlac PDS-1Ds appeared.

**Comment by larsbrinkhoff** [comment]
Picture of the keyboard.
![ards-keyboard](https://user-images.githubusercontent.com/775050/40600844-2497b378-6253-11e8-96fa-b8034a59b0c3.png)

**Comment by larsbrinkhoff** [comment]
@rcornwell, do you see any ARDS code in your copy of CTSS?

**Comment by jh95468** [comment]
IIRC, you probably won't find any ARDS-related code in the CTSS OS itself.  The ARDS was just a terminal, interfaced via RS232, often over dialup.  Graphics were generated by sending appropriate character sequences.  Typing out a normal text file, on a noisy TTY line, could easily cause the ARDS to go into graphics mode and draw abstract art all over the screen.

I wrote a few programs to display enginering graphs as part of a tutorial program.  As I recall, the graphics were mostly handled by a library subroutine package, probably in Algol or maybe Pascal.   So that's where you might find artifacts of ARDS code.

The ARDS was based on a storage oscilloscope, so you didn't get any dynamic graphics.  It was like an Etch-a-Sketch -- you draw on the screen, building up more and more lines.  Then when you want to go on, you clear the screen (with a bright flash) to get a new blank slate.  Same with text or graphics, no scrolling, backspace-erase, etc.

**Comment by larsbrinkhoff** [comment]
The .INFO. file was added in #1020.

**Comment by larsbrinkhoff** [comment]
SUPARD (#1020) can be used to view ARDS files on SUPDUP graphics terminals, including the Knight TV.

**Comment by larsbrinkhoff** [comment]
Information from SAIL: https://www.saildart.org/OLD[H,DOC]

**Comment by larsbrinkhoff** [comment]
SYSTEM; TS3TTY 116 from 1975-11-30 has an ARDS terminal type, %TNARD.  TS3TTY 150 from 1976-09-16 doesn't.

**Comment by jh95468** [comment]
On 1/24/19 2:00 AM, Lars Brinkhoff wrote:
> SYSTEM; TS3TTY 116 from 1975-11-30 has an ARDS terminal type, %TNARD.
> TS3TTY 150 from 1976-09-16 doesn't.

This probably indicates the final demise of the ARDSes.  By 1976,
dynamic display terminals were pretty much the only thing used, except
for the venerable real TTY as the machine console.

In DM, it was Imlacs.  We had come to rely on having terminals that
could run WYSIWIG editors, like EMACS and the MUDDLE editor functions,
which weren't ARDS-friendly.  There was an ARDS on a shelf in the main
terminal room for a long time, not even plugged in.

/Jack Haverty
JFH@MIT-DM ~1970-1977

**Comment by larsbrinkhoff** [comment]
Thanks @jh95468!

I also spotted one in the Architecture Machine group.  The major part of the video is centered on two Imlacs.  
https://youtu.be/JgcfI254xEU?t=265

![ards](https://user-images.githubusercontent.com/775050/51742787-08225c00-209b-11e9-8f1a-fd4db719f69c.png)

**Comment by larsbrinkhoff** [comment]
This is supposedly from somewhere at MIT.  https://youtu.be/Zitsox-Ip-I?t=36  
There is both a Datapoint 3300, and an ARDS.
![dp3300](https://user-images.githubusercontent.com/775050/51766097-f8763800-20d9-11e9-9385-e9fdea0ad40d.png)

**Comment by larsbrinkhoff** [comment]
Sorry, probaby not ARDS.

**Comment by larsbrinkhoff** [comment]
And not a Datapoint either!

**Comment by larsbrinkhoff** [comment]
@mwichary identified the terminal to the right as Tektronix 4002A.

**Comment by larsbrinkhoff** [comment]
From "A Survey of Interactive Graphical Systems for Mathematics".

![map-ards](https://user-images.githubusercontent.com/775050/54191855-04b22b00-44b7-11e9-8def-0a77267933f3.png)

**Comment by larsbrinkhoff** [comment]
According to the "ITS 1.5 Reference Manual" fro 1969, ITS had one ARDS terminal attached.

**Comment by larsbrinkhoff** [comment]
The one at ArchMach.

![](https://webmuseum.mit.edu/mxgis/?kv=131145&style=fullsize)
![](https://webmuseum.mit.edu/mxgis/?kv=74668&style=fullsize)

**Comment by larsbrinkhoff** [comment]
Note that MIT's Electronic Systems Laboratory ("ESL") mentioned above also made the "Kludge" display for the CTSS mainframe.  A PDP-7 with a Type 330 CRT.  
http://www.bitsavers.org/pdf/mit/lcs/tr/MIT-LCS-TR-056.pdf

**Comment by larsbrinkhoff** [comment]
The Multics connexion:
- https://multicians.org/mga.html#ARDS
- https://multicians.org/thvv/globe.html
- https://multicians.org/mgg.html#graphics

**Comment by LegalizeAdulthood** [comment]
> This is supposedly from somewhere at MIT. https://youtu.be/Zitsox-Ip-I?t=36
> There is both a Datapoint 3300, and an ARDS.

The terminal on the left is a [Control Data CC6A9](https://terminals-wiki.org/wiki/index.php/File:CDC_CC6A9_computer2.jpg).  If you look carefully at the video, you can read "CONTROL DATA" just above the keyboard on the left.

**Comment by jh95468** [comment]
There were ARDS terminals in use by non-EE departments at MIT.  I'm not sure how widespread they were, but I had a parttime job as a student in 1968/9 in the Metallurgy Department, to use an ARDS as part of one of their courses.

I used an ARDS connected via dialup to CTSS (the campus timesharing utility of the era).  I had to build a system on CTSS that ran a model of some metallurgy process and graphed the results.   That was interesting since it required figuring out how to make it possible for the model routines (written in one language, maybe Pascal IIRC) to use a subroutine library written in a different language (Fortran?).  Since the languages stored data very differently in memory it involved a lot of weird constructs (like using "illegal" negative indices into arrays and suppressing error checking) to get the different languages' routines to properly handle each others data structures.   Then I helped the students use the system to do their various project assignments.

So there were likely ARDSes elsewhere on campus.  The ARDS provided one of the first relatively inexpensive ways to get graphical displays, which was very useful even though they were static pictures.   Much better than the 'ascii art' techniques of generating graphs on printing terminals.

**Comment by larsbrinkhoff** [comment]
I added an ARDS mode to this terminal emulator originally for a Tektronix 4010:  
https://github.com/rricharz/Tek4010

**Comment by larsbrinkhoff** [comment]
@rricharz, see here for some ARDS information.

**Comment by rricharz** [comment]
Any dated reference for the second picture from the top with the ARDS on a round table with that special mouse?

**Comment by larsbrinkhoff** [comment]
I believe this is the source: http://www.maxhost.org/other/ards-display-terminal-1968.png

But the suggested 1968 dating seems unreliable at best.

**Comment by rricharz** [comment]
I just found this interesting article about the first commercial mouse. It appears that was almost exactly 50 years ago.
  https://www.itworld.com/article/2826241/a-40-year-old-demo-that-still-amazes.html

"Those who saw the original demo and understood Engelbart's vision were blown away. "My heart was in my mouth the whole time," remembers Tom Hagan, CEO of Actioneer. Two years later, the company he worked for had bought Computer Displays Inc. (CDI), the company that sold the first mouse, as part of its ARDS (Advanced Remote Display System) computer."

**Comment by rricharz** [comment]
Page 19 of http://bitsavers.informatik.uni-stuttgart.de/pdf/mitre/ESD_Technical_Reports/ESD-TR-69-358_Microprogramming_Facility_Nov69.pdf shows that the mouse was already available on the ARDS in 1969, and the following shows Engelbart, the inventor of the mouse, with what he calls the "first commercial mouse" from CDI: https://www.cnet.com/pictures/photos-the-mouse-and-even-better-ideas-that-roared-40-years-ago/8/

**Comment by larsbrinkhoff** [comment]
I understand Engelbart invented and designed the first mouse, and Bill English had it built.  But given your information, they must have been quite quick to turn it over to CDI to make a product out of it.

**Comment by larsbrinkhoff** [comment]
Sorry, I have the timeline wrong.  It seems Engelbart and English made the first mouse in 1963, long before The Demo.

**Comment by rricharz** [comment]
Yes, indeed. CDI seems to have been the first company to make a it a product, 1969 or earlier on the ARDS. Anyway, a key event in computer history. It would therefore be very nice to find some software using it on the ARDS.

**Comment by jh95468** [comment]
I used ARDSes in 1969 on CTSS at MIT, but found the mouse to be of marginal use.   The ARDS used a storage-tube display.  So the mouse could move around the single blinking cursor, and use a button to click.  That was useful for some things, but there were many things you couldn't do.  E.g., today;s common "click to select" or "double click to select a word" or "drag" actions weren't possible because the display couldn't do such things.

FYI, circa 1970, Lick brought one of Doug Engelbart's NLS terminals into DM and we put it on the 9th floor attached to DM ITS.  The NLS terminal had a mouse and a five-finger keypad, looking like a small set of piano keys.  There was no keyboard.  To type, you keyed in the ascii codes as 8-bit numbers, using the 3 mouse buttons and the five keypad keys as the 8 binary digits.   Some people (mostly from SRI) had gotten quite good at typing that way but I never got the hang of it.  There was only one NLS terminal, so it never got into common use.   There was some talk of putting the mouse/keypad on our ARDSes for use as "keyboards" but I don't think it ever happened.

**Comment by larsbrinkhoff** [comment]
Wow, an NLS terminal at the 9th floor!  I never heard of such a thing.  The event doesn't seem to have made its way to any records I have read.

Here's are some pretty pictures.  It's actually a mockup.
![nls1](https://user-images.githubusercontent.com/775050/57183959-3e4e5380-6eb4-11e9-83a7-d65628a9bbb4.jpg)

Bill English.  Can we call that a laptop? :-)
![nls2](https://user-images.githubusercontent.com/775050/57183962-44443480-6eb4-11e9-8874-41069206da6e.jpg)

Doug Engelbart.  At a standing desk, he was truly ahead of his time.
![nls3](https://user-images.githubusercontent.com/775050/57183964-4a3a1580-6eb4-11e9-8798-bf256953ad22.jpg)

**Comment by jh95468** [comment]
Curious...   I remember the mouse/keypad, looking exactly as shown in the picture.  But I also remember there was no regular keyboard at all (unlike those pictures), and I don't remember any special display at all.

The NLS setup was on the 9th floor in the DM computer area, right next to the main door from the elevator lobby.  That's also where we had several ARDSes for general use.  Is it possible that what we had was a setup to enable one to use NLS with an ARDS as its display and the mouse/keypad wired in somehow?   

I remember that Lick was very interested in using remote resources over the ARPANET (not surprising if you've read The Dream Machine).   So that "NLS Terminal" I remember may have been a setup to use NLS in California from a terminal at MIT via the ARPANET.   As I recall, NLS was functional but not very responsive, probably because of the cross-country network delays.   I also remember that Lick asked me if I'd like to go spend a few weeks out at Engelbart's lab learning how to use NLS -- but I was having too much fun hacking PDP10 code.

**Comment by larsbrinkhoff** [comment]
http://www.virhistory.com/graphics_hw/index.htm has this information

>Computer Displays Inc - Waltham MA
> - founded 1965? by ?
> - spinoff from MIT Project MAC
> - acquired by Adage 1970?
    ARDS graphics terminal using Tektronix storage tube

![ards-ad](https://user-images.githubusercontent.com/775050/57188600-847dd400-6f01-11e9-9dca-2b87cbe80ef4.jpg)
http://www.dvq.com/ads/cdi_dm_4_70.jpg

**Comment by larsbrinkhoff** [comment]
Also joystick.  From https://www.evl.uic.edu/datsoupi/502/14_mach.pdf

![ards-joy](https://user-images.githubusercontent.com/775050/57188844-babd5280-6f05-11e9-8385-a66a361147bc.png)

**Comment by rricharz** [comment]
Just for reference: I finally identified the original source of the first picture in this thread of the ARDS with the mouse on the round table. It is from the ARDS manual of December 1, 1968. This manual also contains pictures of the mouse itself, and mentions both the mouse and joystick devices.

**Comment by larsbrinkhoff** [comment]
Peter Samson's music program BIG can display scores on an ARDS terminal.  Presumably, it's not yet tested.

**Comment by larsbrinkhoff** [comment]
ITS support for ARDS terminals was dropped 1976 in favor of Tektronix.

**Comment by shirleymarquez** [comment]
The ARDS was also an important reason for the existence of the unusual wrap mode of using a display in ITS rather than the more typical scroll mode. In wrap mode, instead of new text appearing at the bottom and pushing existing text up, the display would pause when reaching the bottom. When the user signaled to continue new text would appear at the top, overwriting the oldest content but leaving lower parts of the screen intact until their turn to be overwritten came along.

Many users of ITS continued to prefer the wrap mode even after switching to more modern display devices. It was also available on the Lisp Machine's terminal software.

**Comment by larsbrinkhoff** [comment]
Thank you.  David Moon commented in #1473:

> It's really hard to read text that is scrolling out from under your gaze. Remember back in the old days transmission from the computer to the terminal was slow, it's not like the screen would scroll for a fraction of a second then stop at --MORE-- to give you a chance to read it. At 2400 baud the screen would jump 3 or 4 times a second if it was scrolling; it would be nauseating and unreadable. That is probably the reason for wrapping around rather than scrolling.

**Comment by drboone** [comment]
Any idea what the front panel in the second photo belongs to?  Angle is too extreme to read the name.

**Comment by jh95468** [comment]
No idea.  FYI, for historians...  There's quite a lot of information contained in the "progress reports" submitted to the government by Project Mac (and I assume other such groups).  Many of these are available now on DTIC as PDFs of scanned microfilm - e.g., see https://discover.dtic.mil/ and type "Project MAC Progress Report" into the search box.   E.g., there are descriptions and diagrams of PDP-10 configurations from various years.

**Comment by larsbrinkhoff** [comment]
@drboone, ArchMach was an Interdata shop.  Compare against this Interdata Model 4.
https://rcsri.org/collection/interdata-4/
![Interdata Model 4](https://rcsri.org/collection/interdata-4/interdata-4.jpg)

**Comment by drboone** [comment]
Yes, that matches perfectly, thanks.
