### ISSUE TITLE
Attach GT40 and/or Imlac emulator

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#870]
These graphical terminals should talk to a PDP-10 over serial lines.

- SIMH has the necessary stuff to emulate a GT40 with a VT11 display.
- sImlac has run Maze War, so it should be ok.

SUDS should be able to use these displays.

**Comment by larsbrinkhoff** [comment]
Hello @rzzzwilson,

What's the status on your Imlac emulator?

**Comment by rzzzwilson** [comment]
Hi Lars,

I haven't touched it in a couple of years.  As I recall, it was running
simple display programs.  I compared the graphical output from a display
test program with some other guy with his own emulator and they were
identical.  I believe I was thinking about switching back to C as an
implementation language as this has better ease of distribution.  Python is
not so good in this respect, though it's more cross-platform.  All the
tools written in python (assembler, test suite, etc) would stay that way.

I suspect you may be interested in Maze War since you are posting from a
PDP-10 forum.  I haven't thought about Maze War since it needs two Imlacs
and a PDP-10, all simulated these days, and I don't know how the original
Imlacs talked to the PDP-10.

Ross

**Comment by larsbrinkhoff** [comment]
Hello Ross,

Thank you.  Actually, I'm more interesting in running SUDS (Stanford's CAD system).  I believe the Imlacs were connected through serial lines and used a simple protocol for ASCII text and escape codes to enter graphics mode.  So this use case is probably much simpler than running Maze War.  I don't know if there is an Imlac program for processing such a protocol?

By the way, this is posted to GitHub.  If you like, you can see https://github.com/PDP-10/its/issues/870 for more info.

**Comment by rzzzwilson** [comment]
Hi Lars,

I haven't seen anything about the SUDS protocol.  There is no example of it
in any Imlac code I've been able to find, either source code or binary.
And certainly no documentation.  There isn't a lot of Imlac software
around.  I'm aware of Tom Uban's repository and a few smaller collections,
but that's all.

Ross

**Comment by larsbrinkhoff** [comment]
GT40 is done.

Imlac is work in progress.  Mostly, we miss a usable version of SSV.

**Comment by larsbrinkhoff** [comment]
Imlac simulator being added in #1502, using SSV 22.

**Comment by larsbrinkhoff** [comment]
Hello again @rzzzwilson, 

You wrote  I'm aware of Tom Uban's repository and a few smaller collections".  What are those other smaller collections?  I'm trying to put everything in one place here:

https://github.com/larsbrinkhoff/imlac-software
