### ISSUE TITLE
FACTOR - factors integers

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/its#96]
SYS1; TS FACTOR
.INFO.;FACTOR ORDER

Source missing?

**Comment by larsbrinkhoff** [comment]
@atsampson, see this:  
https://github.com/PDP-10/its-vault/blob/master/files/rz/factor.26

**Comment by atsampson** [comment]
Neat! Comparing the two, that's definitely a later version of the same program - it uses a lookup table for the keys (including lowercase entries) rather than lots of individual tests, it uses .CALL OPEN rather than .SUSET and .OPEN, and it has a quit command. The maths code is identical.

Is it possible that that code also started life as a disassembly? It flips between using numeric and symbolic names for the registers and IO channels...

Was there an updated FACTOR ORDER with it, with the lowercase keys added? The QUERY code that provides help for a key is still case-sensitive.

**Comment by larsbrinkhoff** [comment]
As far as I can see, the FACTORY ORDER we have is the latest version according to timestamps.

**Comment by atsampson** [comment]
The change to put the TEST inner loop at 100 rather than in the registers looks wrong, looking at the binary it produces -- it does a TRC .+1,6, which can only work when .+1 is in the range 0-17, and an HRRI to the same location later. The code still works by chance, because the value in that location by default is 2, so it just ends up checking every even number as a possible factor (and the TRC/HRRI overwrite A which doesn't matter).

So I wonder if that version never got installed, because the intention was to speed it up on the KL by running the inner loop from main memory rather than the registers, but it actually ended up being slower as it was testing more factors...
