### ISSUE TITLE
1988 ITS distribution terms

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#970]
Looks like these were the terms when ITS tapes were sent to Sweden:

> These tapes contain software and information for the maintenance of the ITS operating system at the Royal Institute of Technology, Sweden.  ITS is distributed free by the Massachusetts Institute of Technology for non-profit, educational purposes only.  This software cannot be resold, and has no commercial value.

**Comment by larsbrinkhoff** [comment]
@36bit, I'll let you chew on this one.

**Comment by 36bit** [comment]
> Aside from the known problem child, INQUIR

Although, for our purposes, it would be helpful to be able to show INQUIR not having one back then too.

**Comment by atsampson** [comment]
It's a non-free (and rather vague) license by modern standards, but it's certainly better than nothing. Do we know what the Swedish ITS tapes contained?

**Comment by larsbrinkhoff** [comment]
Probably these directories:

```
.INFO.;
.TECO.;
C;
COMLAP;
COMMON;
DECSYS;
DEVICE;
EMACS;
EMACS1;
FORMAT;
HUMOR;
INFO;
INQUIR;
KLDCP;
KLH;
KSC;
KSHACK;
L;
LIBDOC;
LIBLSP;
LISP;
LISP20;
LSB;
LSB1;
LSPDMP;
LSPSRC;
MAINT;
MIDAS;
MOON;
NETDOC;
NILCOM;
RWK;
SAIL;
SYS;
SYS1;
SYS2;
SYS3;
SYSBIN;
SYSDOC;
SYSEN1;
SYSEN2;
SYSENG;
SYSHST;
SYSNET;
SYSTEM;
UCODE;

**Comment by 36bit** [comment]
> It's a non-free (and rather vague) license by modern standards, but it's certainly better than nothing.

The license is non-free, yes, but that doesn't necessarily matter: We have to judge it by the standards of the time. U.S. copyright hasn't been a single unmoving monolith for all these years. There's a lot of things to factor in. For example: The U.S. didn't implement automatic copyright (from the Berne Convention) until March 1, 1989. Because things have changed so much over the years Cornell has a nice chart to use: https://copyright.cornell.edu/publicdomain

This situation with a notice purporting to limit distribution but lacking any copyright notices (which is important in the time from before automatic copyright, lest you lost your copyright) reminds me of the lawsuit with Berkeley over UNIX.

http://www.groklaw.net/articlebasic.php?story=20041121063628466 is probably relevant here.

There's a very similar situation with no copyright notices but a separate agreement. There are some very interesting comments in there from the judge.

Sadly USL decided to settle the case with Berkeley instead of pushing forward with it. And so the court never had a chance to rule on that particular matter about the lack of notice.

But, as you can see, the judge seemed skeptical of the copyright claims. I like to think that USL decided it was better to settle with Berkeley rather than continue to try to push it through the court and risk a decision that they'd lost their copyright over UNIX because of not having notices.

Anyway, back to the point here assuming that these same things are present on what we have on GitHub then this example here showing copies being sent without notice in the pre-Berne era helps to strengthen the case I was making in another issue that ITS is probably in the public domain.

That would also mean that MIT's 1999 release under the GPL is probably invalid, since the GPL relies on copyright in order to work, and MIT probably lost their copyright due to noticeless publication before then. But, that's a side thing for geeks like me. There's no benefit for this project to fight that particular point because it doesn't hinder anything for our purposes of being able to share and change ITS. These are both things that could be done whether it's under the GPL or in the public domain.
